# Welcome to BinPan's Basic Tutorial

Some API calls require an API key -- endpoints like the wallet, orders, etc.

BinPan contains no Binance **order method, withdraw method** or any dangerous command.

If you decide to add API keys for using account methods, BinPan will encrypt them in a file and in memory,
but it is recommended not to enable trading capability in the Binance API key configuration, just for your own peace of mind.

Be careful out there!

In [1]:
import binpan

You can add `api_key` and `api_secret` to get more from the API. They are needed to use the Wallet and Exchange classes.

In [2]:
!python -V

Python 3.12.3

In [3]:
binpan.__version__

'0.8.14'

# Get data

Select a symbol, a tick interval, and a time interval -- or just a limit of candles.

Time interval inputs can be a string like `2022-02-14 12:00:00`.

In [4]:
# Fetch the last 200 candles for LTCBTC, 1-minute interval
lun = binpan.Symbol(symbol='LTCUSDT',
                    tick_interval='1m',
                    limit=200,
                    time_zone='Europe/Madrid',
                    closed=True)
lun.df

2026-03-05	 13:30:44     INFO get_candles_by_time_stamps -> symbol=LTCUSDT tick_interval=1m start=2026-03-05 10:09:00 end=2026-03-05 13:29:59 limit=200
2026-03-05 13:30:44     INFO [panzer.binance.public.spot] Inicializando BinancePublicClient(market=spot)
2026-03-05 13:30:46     INFO [panzer.binance.public.spot] Rate limiter inicializado: max_per_minute=6000 safety_ratio=0.90

                                          Open time   Open   High    Low  Close    Volume                       Close time  Quote volume  Trades  Taker buy base volume  Taker buy quote volume  Ignore  Open timestamp  Close timestamp
LTCUSDT 1m Europe/Madrid
2026-03-05 10:09:00+01:00 2026-03-05 10:09:00+01:00  56.65  56.66  56.61  56.64   293.898 2026-03-05 10:09:59.999000+01:00   16647.23122     199                166.529              9431.93062       0   1772701740000    1772701799999
2026-03-05 10:10:00+01:00 2026-03-05 10:10:00+01:00  56.65  56.72  56.65  56.72  1530.599 2026-03-05 10:10:59.999000+01:00   86771.03568     686                554.959             31462.42249       0   1772701800000    1772701859999
2026-03-05 10:11:00+01:00 2026-03-05 10:11:00+01:00  56.73  56.77  56.70  56.76   796.463 2026-03-05 10:11:59.999000+01:00   45181.48278     484                216.006             12256.62990       0   1772701860000    1772701919999
2026-03-05 10:12:00+01:00 2026-03-05 10:12:00+01:00  56.77  56.82  56.74  56.75   650.270 2026-03-05 10:12:59.999000+01:00   36924.02352     522                492.912             27990.08418       0   1772701920000    1772701979999
2026-03-05 10:13:00+01:00 2026-03-05 10:13:00+01:00  56.75  56.77  56.69  56.71   243.862 2026-03-05 10:13:59.999000+01:00   13835.53783     269                134.983              7659.66892       0   1772701980000    1772702039999
...                                             ...    ...    ...    ...    ...       ...                              ...           ...     ...                    ...                     ...     ...             ...              ...
2026-03-05 13:24:00+01:00 2026-03-05 13:24:00+01:00  55.95  55.95  55.93  55.95   180.776 2026-03-05 13:24:59.999000+01:00   10112.88726      81                144.386              8077.25612       0   1772713440000    1772713499999
2026-03-05 13:25:00+01:00 2026-03-05 13:25:00+01:00  55.96  56.01  55.96  55.98   120.664 2026-03-05 13:25:59.999000+01:00    6756.21524     158                 73.215              4099.42236       0   1772713500000    1772713559999
2026-03-05 13:26:00+01:00 2026-03-05 13:26:00+01:00  55.97  55.98  55.96  55.98    64.760 2026-03-05 13:26:59.999000+01:00    3624.37963      61                 16.412               918.61158       0   1772713560000    1772713619999
2026-03-05 13:27:00+01:00 2026-03-05 13:27:00+01:00  55.97  55.97  55.84  55.88  2293.510 2026-03-05 13:27:59.999000+01:00  128202.53650     582                336.377             18797.36294       0   1772713620000    1772713679999
2026-03-05 13:28:00+01:00 2026-03-05 13:28:00+01:00  55.88  55.91  55.87  55.91   166.493 2026-03-05 13:28:59.999000+01:00    9304.53458     101                153.898              8600.68661       0   1772713680000    1772713739999

[200 rows x 14 columns]

In [5]:
list(lun.df.columns)

['Open time',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'Close time',
 'Quote volume',
 'Trades',
 'Taker buy base volume',
 'Taker buy quote volume',
 'Ignore',
 'Open timestamp',
 'Close timestamp']

# Indicators

Another Jupyter Notebook is available with more examples about indicators.

Let's add some technical indicators.

In [6]:
lun.ema(21)

2026-03-05	 13:30:48     INFO New column: EMA_21

LTCUSDT 1m Europe/Madrid
2026-03-05 10:09:00+01:00    56.640000
2026-03-05 10:10:00+01:00    56.647273
2026-03-05 10:11:00+01:00    56.657521
2026-03-05 10:12:00+01:00    56.665928
2026-03-05 10:13:00+01:00    56.669934
                               ...
2026-03-05 13:24:00+01:00    55.999567
2026-03-05 13:25:00+01:00    55.997788
2026-03-05 13:26:00+01:00    55.996171
2026-03-05 13:27:00+01:00    55.985610
2026-03-05 13:28:00+01:00    55.978736
Name: EMA_21, Length: 200, dtype: float64

In [7]:
lun.supertrend()

2026-03-05	 13:30:49     INFO New column: SUPERT_10_3
2026-03-05	 13:30:49     INFO New column: SUPERTd_10_3
2026-03-05	 13:30:49     INFO New column: SUPERTl_10_3
2026-03-05	 13:30:49     INFO New column: SUPERTs_10_3

                           SUPERT_10_3  SUPERTd_10_3  SUPERTl_10_3  SUPERTs_10_3
LTCUSDT 1m Europe/Madrid
2026-03-05 10:09:00+01:00    56.485000           1.0      56.48500           NaN
2026-03-05 10:10:00+01:00    56.526000           1.0      56.52600           NaN
2026-03-05 10:11:00+01:00    56.570900           1.0      56.57090           NaN
2026-03-05 10:12:00+01:00    56.608310           1.0      56.60831           NaN
2026-03-05 10:13:00+01:00    56.608310           1.0      56.60831           NaN
...                                ...           ...           ...           ...
2026-03-05 13:24:00+01:00    56.067492          -1.0           NaN     56.067492
2026-03-05 13:25:00+01:00    56.067492          -1.0           NaN     56.067492
2026-03-05 13:26:00+01:00    56.067492          -1.0           NaN     56.067492
2026-03-05 13:27:00+01:00    56.067492          -1.0           NaN     56.067492
2026-03-05 13:28:00+01:00    56.067492          -1.0           NaN     56.067492

[200 rows x 4 columns]

By default, technical indicators are added to the instance with the argument `inplace=True`.

In [8]:
lun.df

                                          Open time   Open   High    Low  Close    Volume                       Close time  Quote volume  Trades  Taker buy base volume  Taker buy quote volume  Ignore  Open timestamp  Close timestamp     EMA_21  SUPERT_10_3  SUPERTd_10_3  SUPERTl_10_3  SUPERTs_10_3
LTCUSDT 1m Europe/Madrid
2026-03-05 10:09:00+01:00 2026-03-05 10:09:00+01:00  56.65  56.66  56.61  56.64   293.898 2026-03-05 10:09:59.999000+01:00   16647.23122     199                166.529              9431.93062       0   1772701740000    1772701799999  56.640000    56.485000           1.0      56.48500           NaN
2026-03-05 10:10:00+01:00 2026-03-05 10:10:00+01:00  56.65  56.72  56.65  56.72  1530.599 2026-03-05 10:10:59.999000+01:00   86771.03568     686                554.959             31462.42249       0   1772701800000    1772701859999  56.647273    56.526000           1.0      56.52600           NaN
2026-03-05 10:11:00+01:00 2026-03-05 10:11:00+01:00  56.73  56.77  56.70  56.76   796.463 2026-03-05 10:11:59.999000+01:00   45181.48278     484                216.006             12256.62990       0   1772701860000    1772701919999  56.657521    56.570900           1.0      56.57090           NaN
2026-03-05 10:12:00+01:00 2026-03-05 10:12:00+01:00  56.77  56.82  56.74  56.75   650.270 2026-03-05 10:12:59.999000+01:00   36924.02352     522                492.912             27990.08418       0   1772701920000    1772701979999  56.665928    56.608310           1.0      56.60831           NaN
2026-03-05 10:13:00+01:00 2026-03-05 10:13:00+01:00  56.75  56.77  56.69  56.71   243.862 2026-03-05 10:13:59.999000+01:00   13835.53783     269                134.983              7659.66892       0   1772701980000    1772702039999  56.669934    56.608310           1.0      56.60831           NaN
...                                             ...    ...    ...    ...    ...       ...                              ...           ...     ...                    ...                     ...     ...             ...              ...        ...          ...           ...           ...           ...
2026-03-05 13:24:00+01:00 2026-03-05 13:24:00+01:00  55.95  55.95  55.93  55.95   180.776 2026-03-05 13:24:59.999000+01:00   10112.88726      81                144.386              8077.25612       0   1772713440000    1772713499999  55.999567    56.067492          -1.0           NaN     56.067492
2026-03-05 13:25:00+01:00 2026-03-05 13:25:00+01:00  55.96  56.01  55.96  55.98   120.664 2026-03-05 13:25:59.999000+01:00    6756.21524     158                 73.215              4099.42236       0   1772713500000    1772713559999  55.997788    56.067492          -1.0           NaN     56.067492
2026-03-05 13:26:00+01:00 2026-03-05 13:26:00+01:00  55.97  55.98  55.96  55.98    64.760 2026-03-05 13:26:59.999000+01:00    3624.37963      61                 16.412               918.61158       0   1772713560000    1772713619999  55.996171    56.067492          -1.0           NaN     56.067492
2026-03-05 13:27:00+01:00 2026-03-05 13:27:00+01:00  55.97  55.97  55.84  55.88  2293.510 2026-03-05 13:27:59.999000+01:00  128202.53650     582                336.377             18797.36294       0   1772713620000    1772713679999  55.985610    56.067492          -1.0           NaN     56.067492
2026-03-05 13:28:00+01:00 2026-03-05 13:28:00+01:00  55.88  55.91  55.87  55.91   166.493 2026-03-05 13:28:59.999000+01:00    9304.53458     101                153.898              8600.68661       0   1772713680000    1772713739999  55.978736    56.067492          -1.0           NaN     56.067492

[200 rows x 19 columns]

# Plots

Another Jupyter Notebook is available with more examples about plotting.

These are the very basics.

In [9]:
lun.plot()

'/home/nando/PycharmProjects/binpan_studio_dev/last_plot.png'

# Trades

Trades can be downloaded for the time period of the instance.

**Beware of requesting large time periods.**

BinPan monitors the API weight and waits if it is approaching the limit.

In [10]:
lun.get_atomic_trades()

2026-03-05	 13:30:52     INFO Obteniendo atomic trades de LTCUSDT por tiempo: 2026-03-05 09:09:00.000000 -> 2026-03-05 12:28:00.000000

Requesting atomic trades between 2026-03-05 10:09:00 and 2026-03-05 13:28:00

2026-03-05	 13:30:53     INFO Rango de IDs atómicos descubierto para LTCUSDT: 566519596 -> 566551064 (estimado 31469 trades)
2026-03-05	 13:30:54     INFO Peticiones API atomic trades LTCUSDT: 1 (ID actual: 566520596)
2026-03-05	 13:30:54     INFO Peticiones API atomic trades LTCUSDT: 2 (ID actual: 566521596)
2026-03-05	 13:30:55     INFO Peticiones API atomic trades LTCUSDT: 3 (ID actual: 566522596)
2026-03-05	 13:30:55     INFO Peticiones API atomic trades LTCUSDT: 4 (ID actual: 566523596)
2026-03-05	 13:30:55     INFO Peticiones API atomic trades LTCUSDT: 5 (ID actual: 566524596)
2026-03-05	 13:30:55     INFO Peticiones API atomic trades LTCUSDT: 6 (ID actual: 566525596)
2026-03-05	 13:30:56     INFO Peticiones API atomic trades LTCUSDT: 7 (ID actual: 566526596)
2026-03-05	 13:30:56     INFO Peticiones API atomic trades LTCUSDT: 8 (ID actual: 566527596)
2026-03-05	 13:30:56     INFO Peticiones API atomic trades LTCUSDT: 9 (ID actual: 566528596)
2026-03-05	 13:30:56     INFO Peticiones API atomic trades LTCUSDT: 10 (ID actual: 566529596)
2026-03-05	 13:30:57     INFO Peticiones API atomic trades LTCUSDT: 11 (ID actual: 566530596)
2026-03-05	 13:30:57     INFO Peticiones API atomic trades LTCUSDT: 12 (ID actual: 566531596)
2026-03-05	 13:30:57     INFO Peticiones API atomic trades LTCUSDT: 13 (ID actual: 566532596)
2026-03-05	 13:30:57     INFO Peticiones API atomic trades LTCUSDT: 14 (ID actual: 566533596)
2026-03-05	 13:30:58     INFO Peticiones API atomic trades LTCUSDT: 15 (ID actual: 566534596)
2026-03-05	 13:30:58     INFO Peticiones API atomic trades LTCUSDT: 16 (ID actual: 566535596)
2026-03-05	 13:30:58     INFO Peticiones API atomic trades LTCUSDT: 17 (ID actual: 566536596)
2026-03-05	 13:30:59     INFO Peticiones API atomic trades LTCUSDT: 18 (ID actual: 566537596)
2026-03-05	 13:30:59     INFO Peticiones API atomic trades LTCUSDT: 19 (ID actual: 566538596)
2026-03-05	 13:30:59     INFO Peticiones API atomic trades LTCUSDT: 20 (ID actual: 566539596)
2026-03-05	 13:30:59     INFO Peticiones API atomic trades LTCUSDT: 21 (ID actual: 566540596)
2026-03-05	 13:31:00     INFO Peticiones API atomic trades LTCUSDT: 22 (ID actual: 566541596)
2026-03-05	 13:31:00     INFO Peticiones API atomic trades LTCUSDT: 23 (ID actual: 566542596)
2026-03-05	 13:31:00     INFO Peticiones API atomic trades LTCUSDT: 24 (ID actual: 566543596)
2026-03-05	 13:31:00     INFO Peticiones API atomic trades LTCUSDT: 25 (ID actual: 566544596)
2026-03-05	 13:31:01     INFO Peticiones API atomic trades LTCUSDT: 26 (ID actual: 566545596)
2026-03-05	 13:31:01     INFO Peticiones API atomic trades LTCUSDT: 27 (ID actual: 566546596)
2026-03-05	 13:31:01     INFO Peticiones API atomic trades LTCUSDT: 28 (ID actual: 566547596)
2026-03-05	 13:31:01     INFO Peticiones API atomic trades LTCUSDT: 29 (ID actual: 566548596)
2026-03-05	 13:31:02     INFO Peticiones API atomic trades LTCUSDT: 30 (ID actual: 566549596)
2026-03-05	 13:31:02     INFO Peticiones API atomic trades LTCUSDT: 31 (ID actual: 566550596)
2026-03-05	 13:31:02     INFO Peticiones API atomic trades LTCUSDT: 32 (ID actual: 566551596)
2026-03-05	 13:31:02     INFO Atomic trades LTCUSDT: 32 peticiones, 32000 trades obtenidos

                        Trade Id  Price  Quantity  Quote quantity                 Date      Timestamp  Buyer was maker  Best price match
LTCUSDT Europe/Madrid
0                      566519596  56.65     0.106         6.00490  2026-03-05 10:09:01  1772701741984             True              True
1                      566519597  56.65     0.092         5.21180  2026-03-05 10:09:01  1772701741984             True              True
2                      566519598  56.65     0.177        10.02705  2026-03-05 10:09:01  1772701741984             True              True
3                      566519599  56.65     0.093         5.26845  2026-03-05 10:09:01  1772701741984             True              True
4                      566519600  56.65     0.093         5.26845  2026-03-05 10:09:01  1772701741984             True              True
...                          ...    ...       ...             ...                  ...            ...              ...               ...
31995                  566551591  56.39     0.991        55.88249  2026-03-05 12:37:18  1772710638172            False              True
31996                  566551592  56.39     0.092         5.18788  2026-03-05 12:37:18  1772710638186            False              True
31997                  566551593  56.39     0.836        47.14204  2026-03-05 12:37:18  1772710638214            False              True
31998                  566551594  56.39     3.228       182.02692  2026-03-05 12:37:18  1772710638314            False              True
31999                  566551595  56.39     0.607        34.22873  2026-03-05 12:37:18  1772710638314            False              True

[32000 rows x 8 columns]

In [11]:
lun.get_agg_trades(minutes=60)

2026-03-05	 13:31:03     INFO Obteniendo aggTrades de LTCUSDT por tiempo: 2026-03-05 11:31:03.062000 -> 2026-03-05 12:28:00.000000

Requesting aggregated trades between 2026-03-05 12:31:03 and 2026-03-05 13:28:00

2026-03-05	 13:31:04     INFO aggTrades LTCUSDT: 5 peticiones, 4426 trades obtenidos

                       Aggregate tradeId  Price  Quantity  First tradeId  Last tradeId                 Date      Timestamp  Buyer was maker  Best price match
LTCUSDT Europe/Madrid
0                              324275319  56.58     0.458      566549135     566549137  2026-03-05 12:31:03  1772710263084            False              True
1                              324275320  56.58     0.539      566549138     566549138  2026-03-05 12:31:03  1772710263120            False              True
2                              324275321  56.57     0.164      566549139     566549139  2026-03-05 12:31:04  1772710264262             True              True
3                              324275322  56.57    32.000      566549140     566549146  2026-03-05 12:31:06  1772710266834             True              True
4                              324275323  56.57     0.093      566549147     566549147  2026-03-05 12:31:06  1772710266835             True              True
...                                  ...    ...       ...            ...           ...                  ...            ...              ...               ...
4421                           324279741  55.87     0.327      566563173     566563173  2026-03-05 13:27:51  1772713671245            False              True
4422                           324279742  55.87     0.358      566563174     566563174  2026-03-05 13:27:53  1772713673449            False              True
4423                           324279743  55.87     1.060      566563175     566563184  2026-03-05 13:27:55  1772713675166            False              True
4424                           324279744  55.87    38.738      566563185     566563188  2026-03-05 13:27:56  1772713676922             True              True
4425                           324279745  55.88     0.922      566563189     566563197  2026-03-05 13:27:56  1772713676923            False              True

[4426 rows x 9 columns]

# Plots with trades

Using `plot_agg_trades_size()`, you can visualize the size of aggregated trades. Useful for finding whale operations or support/resistance levels.

In [12]:
lun.plot_agg_trades_size()

'/home/nando/PycharmProjects/binpan_studio_dev/last_plot.png'

# Support and resistance levels with trades

In [13]:
lun.support_resistance(from_atomic=True, by_quantity=True)

2026-03-05	 13:31:06  WARNING Clustering data...
2026-03-05	 13:31:06     INFO Updating support_resistance levels for LTCUSDT from atomic trades

([56.51529518064342,
  56.6718141912617,
  56.82172723270752,
  56.95344806814595,
  57.090952508767096],
 [])

In [14]:
lun.plot()

'/home/nando/PycharmProjects/binpan_studio_dev/last_plot.png'

# Fetching exchange data

There is a dedicated class called `Exchange` in BinPan for these tasks, but the `Symbol` class can also retrieve some exchange data.

In [15]:
lun.get_order_filters()

{'PRICE_FILTER_minPrice': '0.01000000',
 'PRICE_FILTER_maxPrice': '100000.00000000',
 'PRICE_FILTER_tickSize': '0.01000000',
 'LOT_SIZE_minQty': '0.00100000',
 'LOT_SIZE_maxQty': '90000.00000000',
 'LOT_SIZE_stepSize': '0.00100000',
 'ICEBERG_PARTS_limit': 50,
 'MARKET_LOT_SIZE_minQty': '0.00000000',
 'MARKET_LOT_SIZE_maxQty': '11881.91305439',
 'MARKET_LOT_SIZE_stepSize': '0.00000000',
 'TRAILING_DELTA_minTrailingAboveDelta': 10,
 'TRAILING_DELTA_maxTrailingAboveDelta': 2000,
 'TRAILING_DELTA_minTrailingBelowDelta': 10,
 'TRAILING_DELTA_maxTrailingBelowDelta': 2000,
 'PERCENT_PRICE_BY_SIDE_bidMultiplierUp': '2',
 'PERCENT_PRICE_BY_SIDE_bidMultiplierDown': '0.5',
 'PERCENT_PRICE_BY_SIDE_askMultiplierUp': '2',
 'PERCENT_PRICE_BY_SIDE_askMultiplierDown': '0.5',
 'PERCENT_PRICE_BY_SIDE_avgPriceMins': 5,
 'NOTIONAL_minNotional': '5.00000000',
 'NOTIONAL_applyMinToMarket': True,
 'NOTIONAL_maxNotional': '9000000.00000000',
 'NOTIONAL_applyMaxToMarket': False,
 'NOTIONAL_avgPriceMins': 5,
 'MAX_NUM_ORDERS_maxNumOrders': 200,
 'MAX_NUM_ORDER_LISTS_maxNumOrderLists': 20,
 'MAX_NUM_ALGO_ORDERS_maxNumAlgoOrders': 5,
 'MAX_NUM_ORDER_AMENDS_maxNumOrderAmends': 10}

In [16]:
lun.get_order_types()

['LIMIT',
 'LIMIT_MAKER',
 'MARKET',
 'STOP_LOSS',
 'STOP_LOSS_LIMIT',
 'TAKE_PROFIT',
 'TAKE_PROFIT_LIMIT']

In [17]:
lun.get_permissions()

['TRD_GRP_071',
 'TRD_GRP_061',
 'TRD_GRP_199',
 'TRD_GRP_238',
 'TRD_GRP_080',
 'TRD_GRP_200',
 'TRD_GRP_171',
 'TRD_GRP_181',
 'TRD_GRP_197',
 'TRD_GRP_215',
 'TRD_GRP_247',
 'TRD_GRP_006',
 'TRD_GRP_145',
 'TRD_GRP_109',
 'TRD_GRP_134',
 'TRD_GRP_084',
 'TRD_GRP_180',
 'TRD_GRP_164',
 'TRD_GRP_154',
 'TRD_GRP_228',
 'TRD_GRP_231',
 'TRD_GRP_017',
 'TRD_GRP_049',
 'TRD_GRP_129',
 'TRD_GRP_191',
 'TRD_GRP_176',
 'TRD_GRP_222',
 'TRD_GRP_219',
 'TRD_GRP_150',
 'TRD_GRP_237',
 'TRD_GRP_140',
 'TRD_GRP_136',
 'TRD_GRP_185',
 'TRD_GRP_113',
 'SPOT',
 'TRD_GRP_098',
 'TRD_GRP_174',
 'TRD_GRP_183',
 'TRD_GRP_091',
 'TRD_GRP_107',
 'TRD_GRP_118',
 'TRD_GRP_135',
 'TRD_GRP_116',
 'TRD_GRP_165',
 'TRD_GRP_225',
 'TRD_GRP_004',
 'TRD_GRP_050',
 'TRD_GRP_015',
 'TRD_GRP_250',
 'TRD_GRP_056',
 'TRD_GRP_218',
 'TRD_GRP_090',
 'TRD_GRP_023',
 'TRD_GRP_162',
 'TRD_GRP_142',
 'TRD_GRP_172',
 'TRD_GRP_186',
 'TRD_GRP_253',
 'TRD_GRP_234',
 'TRD_GRP_243',
 'TRD_GRP_202',
 'TRD_GRP_220',
 'TRD_GRP_096',
 'TRD_GRP_175',
 'TRD_GRP_211',
 'TRD_GRP_065',
 'TRD_GRP_210',
 'TRD_GRP_104',
 'TRD_GRP_182',
 'TRD_GRP_121',
 'TRD_GRP_170',
 'TRD_GRP_221',
 'TRD_GRP_058',
 'TRD_GRP_163',
 'TRD_GRP_088',
 'TRD_GRP_128',
 'TRD_GRP_022',
 'TRD_GRP_122',
 'TRD_GRP_204',
 'TRD_GRP_059',
 'TRD_GRP_188',
 'TRD_GRP_057',
 'TRD_GRP_214',
 'TRD_GRP_082',
 'TRD_GRP_168',
 'TRD_GRP_184',
 'TRD_GRP_153',
 'TRD_GRP_115',
 'TRD_GRP_024',
 'TRD_GRP_159',
 'TRD_GRP_085',
 'TRD_GRP_239',
 'TRD_GRP_069',
 'TRD_GRP_074',
 'TRD_GRP_144',
 'TRD_GRP_152',
 'TRD_GRP_064',
 'TRD_GRP_149',
 'TRD_GRP_173',
 'TRD_GRP_251',
 'TRD_GRP_100',
 'TRD_GRP_025',
 'TRD_GRP_146',
 'TRD_GRP_052',
 'TRD_GRP_111',
 'TRD_GRP_158',
 'TRD_GRP_224',
 'TRD_GRP_252',
 'TRD_GRP_106',
 'TRD_GRP_248',
 'TRD_GRP_232',
 'TRD_GRP_051',
 'TRD_GRP_114',
 'TRD_GRP_117',
 'TRD_GRP_123',
 'TRD_GRP_236',
 'TRD_GRP_160',
 'TRD_GRP_166',
 'TRD_GRP_161',
 'TRD_GRP_005',
 'TRD_GRP_068',
 'TRD_GRP_070',
 'TRD_GRP_127',
 'TRD_GRP_072',
 'TRD_GRP_245',
 'TRD_GRP_077',
 'TRD_GRP_124',
 'TRD_GRP_120',
 'TRD_GRP_233',
 'TRD_GRP_110',
 'TRD_GRP_133',
 'TRD_GRP_079',
 'TRD_GRP_213',
 'TRD_GRP_067',
 'TRD_GRP_190',
 'TRD_GRP_249',
 'TRD_GRP_055',
 'TRD_GRP_223',
 'TRD_GRP_208',
 'TRD_GRP_139',
 'TRD_GRP_089',
 'TRD_GRP_020',
 'TRD_GRP_227',
 'TRD_GRP_092',
 'TRD_GRP_102',
 'TRD_GRP_054',
 'TRD_GRP_194',
 'TRD_GRP_235',
 'TRD_GRP_216',
 'TRD_GRP_125',
 'TRD_GRP_081',
 'TRD_GRP_130',
 'TRD_GRP_141',
 'TRD_GRP_246',
 'TRD_GRP_189',
 'TRD_GRP_103',
 'TRD_GRP_156',
 'MARGIN',
 'TRD_GRP_151',
 'TRD_GRP_167',
 'TRD_GRP_187',
 'TRD_GRP_169',
 'TRD_GRP_087',
 'TRD_GRP_137',
 'TRD_GRP_086',
 'TRD_GRP_157',
 'TRD_GRP_078',
 'TRD_GRP_062',
 'TRD_GRP_021',
 'TRD_GRP_066',
 'TRD_GRP_126',
 'TRD_GRP_178',
 'TRD_GRP_177',
 'TRD_GRP_016',
 'TRD_GRP_217',
 'TRD_GRP_242',
 'TRD_GRP_019',
 'TRD_GRP_143',
 'TRD_GRP_198',
 'TRD_GRP_193',
 'TRD_GRP_203',
 'TRD_GRP_105',
 'TRD_GRP_179',
 'TRD_GRP_095',
 'TRD_GRP_196',
 'TRD_GRP_108',
 'TRD_GRP_148',
 'TRD_GRP_207',
 'TRD_GRP_053',
 'TRD_GRP_094',
 'TRD_GRP_209',
 'TRD_GRP_138',
 'TRD_GRP_230',
 'TRD_GRP_201',
 'TRD_GRP_075',
 'TRD_GRP_192',
 'TRD_GRP_240',
 'TRD_GRP_244',
 'TRD_GRP_018',
 'TRD_GRP_060',
 'TRD_GRP_099',
 'TRD_GRP_229',
 'TRD_GRP_205',
 'TRD_GRP_206',
 'TRD_GRP_132',
 'TRD_GRP_097',
 'TRD_GRP_073',
 'TRD_GRP_131',
 'TRD_GRP_076',
 'TRD_GRP_093',
 'TRD_GRP_155',
 'TRD_GRP_083',
 'TRD_GRP_195',
 'TRD_GRP_063',
 'TRD_GRP_112',
 'TRD_GRP_212',
 'TRD_GRP_226',
 'TRD_GRP_101',
 'TRD_GRP_147',
 'TRD_GRP_119']

In [18]:
lun.get_precision()

{'baseAssetPrecision': 8,
 'quoteAssetPrecision': 8,
 'baseCommissionPrecision': 8,
 'quoteCommissionPrecision': 8}

# Other interesting data

In [19]:
lun.plot_market_profile(from_atomic_trades=True)

'/home/nando/PycharmProjects/binpan_studio_dev/last_plot.png'

### Thank you.