In [1]:
!python -V

Python 3.12.3

In [2]:
import binpan
binpan.__version__

'0.8.14'

# Create a Symbol Instance

The `Symbol` class is the main entry point in BinPan. It fetches candlestick (kline) data from the Binance API for a given trading pair and timeframe. The resulting DataFrame contains OHLCV data plus metadata like timestamps and taker volumes.

Key parameters:
- `symbol`: the trading pair (e.g. `"LTCBTC"`)
- `tick_interval`: candle timeframe (`"1m"`, `"5m"`, `"1h"`, `"1d"`, etc.)
- `time_zone`: display timezone for the index
- `limit`: number of candles to fetch

In [3]:
symbol = "dotusdc"
tick_interval = "1m"

In [4]:
sym = binpan.Symbol(symbol=symbol, tick_interval=tick_interval, time_zone="Europe/Madrid", limit = 500)
sym.df

2026-03-05	 14:02:46     INFO get_candles_by_time_stamps -> symbol=DOTUSDC tick_interval=1m start=2026-03-05 05:41:00 end=2026-03-05 14:01:59 limit=500
2026-03-05 14:02:46     INFO [panzer.binance.public.spot] Inicializando BinancePublicClient(market=spot)
2026-03-05 14:02:48     INFO [panzer.binance.public.spot] Rate limiter inicializado: max_per_minute=6000 safety_ratio=0.90

                                          Open time   Open   High    Low  Close  Volume                       Close time  Quote volume  Trades  Taker buy base volume  Taker buy quote volume  Ignore  Open timestamp  Close timestamp
DOTUSDC 1m Europe/Madrid
2026-03-05 05:41:00+01:00 2026-03-05 05:41:00+01:00  1.541  1.541  1.541  1.541  223.59 2026-03-05 05:41:59.999000+01:00     344.55219       9                  16.65                25.65765       0   1772685660000    1772685719999
2026-03-05 05:42:00+01:00 2026-03-05 05:42:00+01:00  1.541  1.541  1.540  1.541  910.18 2026-03-05 05:42:59.999000+01:00    1402.29038      11                 431.76               665.32375       0   1772685720000    1772685779999
2026-03-05 05:43:00+01:00 2026-03-05 05:43:00+01:00  1.541  1.541  1.540  1.541  142.17 2026-03-05 05:43:59.999000+01:00     219.07260       3                   0.00                 0.00000       0   1772685780000    1772685839999
2026-03-05 05:44:00+01:00 2026-03-05 05:44:00+01:00  1.542  1.543  1.542  1.543  264.12 2026-03-05 05:44:59.999000+01:00     407.51246      10                  40.64                62.68282       0   1772685840000    1772685899999
2026-03-05 05:45:00+01:00 2026-03-05 05:45:00+01:00  1.544  1.547  1.544  1.546  319.77 2026-03-05 05:45:59.999000+01:00     494.21649      21                 144.93               223.88816       0   1772685900000    1772685959999
...                                             ...    ...    ...    ...    ...     ...                              ...           ...     ...                    ...                     ...     ...             ...              ...
2026-03-05 13:56:00+01:00 2026-03-05 13:56:00+01:00  1.529  1.529  1.529  1.529    3.47 2026-03-05 13:56:59.999000+01:00       5.30563       1                   0.00                 0.00000       0   1772715360000    1772715419999
2026-03-05 13:57:00+01:00 2026-03-05 13:57:00+01:00  1.530  1.530  1.530  1.530  123.70 2026-03-05 13:57:59.999000+01:00     189.26100       1                 123.70               189.26100       0   1772715420000    1772715479999
2026-03-05 13:58:00+01:00 2026-03-05 13:58:00+01:00  1.530  1.530  1.530  1.530    0.00 2026-03-05 13:58:59.999000+01:00       0.00000       0                   0.00                 0.00000       0   1772715480000    1772715539999
2026-03-05 13:59:00+01:00 2026-03-05 13:59:00+01:00  1.530  1.530  1.528  1.528   40.19 2026-03-05 13:59:59.999000+01:00      61.44664       4                  11.63                17.79390       0   1772715540000    1772715599999
2026-03-05 14:00:00+01:00 2026-03-05 14:00:00+01:00  1.529  1.530  1.529  1.530   16.43 2026-03-05 14:00:59.999000+01:00      25.12929       4                  16.43                25.12929       0   1772715600000    1772715659999

[500 rows x 14 columns]

# Add Technical Indicators

BinPan provides built-in technical indicators that are added as new columns to the Symbol's DataFrame. Here we add:
- **EMA (Exponential Moving Average)**: a trend-following indicator with a 200-period window.
- **VWAP (Volume-Weighted Average Price)**: cumulative over the data range, it shows the average price weighted by volume and is commonly used as a reference for fair value.

Indicators added with `inplace=True` (the default) are automatically included in subsequent `sym.plot()` calls.

In [5]:
sym.ema(200)
sym.vwap()

2026-03-05	 14:02:50     INFO New column: EMA_200
2026-03-05	 14:02:50     INFO New column: VWAP_D

DOTUSDC 1m Europe/Madrid
2026-03-05 05:41:00+01:00    1.541000
2026-03-05 05:42:00+01:00    1.540732
2026-03-05 05:43:00+01:00    1.540725
2026-03-05 05:44:00+01:00    1.541058
2026-03-05 05:45:00+01:00    1.541850
                               ...
2026-03-05 13:56:00+01:00    1.529492
2026-03-05 13:57:00+01:00    1.529492
2026-03-05 13:58:00+01:00    1.529492
2026-03-05 13:59:00+01:00    1.529492
2026-03-05 14:00:00+01:00    1.529492
Name: VWAP_D, Length: 500, dtype: float64

In [6]:
sym.plot()

'/home/nando/PycharmProjects/binpan_studio_dev/last_plot.png'

# Atomic Trades Analysis

Atomic trades are the individual (non-aggregated) trades that occurred during the kline period. By fetching them, we can analyze the actual trade sizes and identify large buyers or sellers.

The `plot_atomic_trades_size()` method renders a bubble chart where bubble size represents trade quantity, allowing visual identification of significant market participants.

In [7]:
sym.get_atomic_trades()

2026-03-05	 14:02:52     INFO Obteniendo atomic trades de DOTUSDC por tiempo: 2026-03-05 04:41:00.000000 -> 2026-03-05 13:00:00.000000

Requesting atomic trades between 2026-03-05 05:41:00 and 2026-03-05 14:00:00

2026-03-05	 14:02:53     INFO Rango de IDs atómicos descubierto para DOTUSDC: 12613674 -> 12616764 (estimado 3091 trades)
2026-03-05	 14:02:54     INFO Peticiones API atomic trades DOTUSDC: 1 (ID actual: 12614674)
2026-03-05	 14:02:55     INFO Peticiones API atomic trades DOTUSDC: 2 (ID actual: 12615674)
2026-03-05	 14:02:55     INFO Peticiones API atomic trades DOTUSDC: 3 (ID actual: 12616674)
2026-03-05	 14:02:55     INFO Peticiones API atomic trades DOTUSDC: 4 (ID actual: 12616775)
2026-03-05	 14:02:55     INFO Atomic trades DOTUSDC: 4 peticiones, 3101 trades obtenidos

                       Trade Id  Price  Quantity  Quote quantity                 Date      Timestamp  Buyer was maker  Best price match
DOTUSDC Europe/Madrid
0                      12613674  1.541      4.26         6.56466  2026-03-05 05:41:27  1772685687580            False              True
1                      12613675  1.541      3.40         5.23940  2026-03-05 05:41:27  1772685687580            False              True
2                      12613676  1.541      8.99        13.85359  2026-03-05 05:41:27  1772685687580            False              True
3                      12613677  1.541     31.83        49.05003  2026-03-05 05:41:28  1772685688383             True              True
4                      12613678  1.541     25.08        38.64828  2026-03-05 05:41:28  1772685688387             True              True
...                         ...    ...       ...             ...                  ...            ...              ...               ...
3086                   12616760  1.530    123.70       189.26100  2026-03-05 13:57:00  1772715420816            False              True
3087                   12616761  1.530     11.63        17.79390  2026-03-05 13:59:49  1772715589361            False              True
3088                   12616762  1.529      6.53         9.98437  2026-03-05 13:59:52  1772715592540             True              True
3089                   12616763  1.529      6.53         9.98437  2026-03-05 13:59:52  1772715592543             True              True
3090                   12616764  1.528     15.50        23.68400  2026-03-05 13:59:54  1772715594045             True              True

[3091 rows x 8 columns]

In [8]:
sym.plot_atomic_trades_size(logarithmic=True, max_size=40)

'/home/nando/PycharmProjects/binpan_studio_dev/last_plot.png'

In the chart above, each trade is represented as a bubble whose size corresponds to the trade quantity. Color distinguishes taker buyers from taker sellers. The relationship between bubble size and price action reveals:
- **Exhaustion**: large taker buy volume without a corresponding price increase suggests buyer exhaustion.
- **Strength**: large taker buy volume followed by a price increase indicates strong buying pressure.
- **Hidden activity**: sometimes large taker buy entries are actually stop-loss executions or cancellations from the makers' side.

## Market Profile

The market profile aggregates volume at each price level, showing where the most trading activity occurred. This helps identify high-volume nodes (areas of price acceptance) and low-volume nodes (areas of price rejection).

In [9]:
sym.plot_market_profile(from_atomic_trades=True)

'/home/nando/PycharmProjects/binpan_studio_dev/last_plot.png'

# Support and Resistance Levels

BinPan uses K-Means clustering on trade data to identify price levels where significant volume has accumulated. These levels often act as support or resistance zones.

The `support_resistance()` method returns lists of support and resistance price centroids (the center of each cluster, representing the most representative price for that zone). When `from_atomic=True`, it uses the granular atomic trade data for more precise level detection.

In [10]:
sym.support_resistance(from_atomic=True)

2026-03-05	 14:02:57  WARNING Clustering data...
2026-03-05	 14:02:57     INFO Updating support_resistance levels for DOTUSDC from atomic trades

([1.5158153809774584,
  1.5214844547896516,
  1.5295434127019774,
  1.540868331454109,
  1.5499591158180448],
 [])

Once support and resistance levels are computed, they are automatically overlaid on the candlestick chart when calling `sym.plot()`. The horizontal lines mark the cluster centroids where the highest trade volume concentration was detected.

## Order Book Density

The order book snapshot shows the current distribution of limit orders (bids and asks) at different price levels, providing insight into near-term supply and demand zones.

In [11]:
sym.plot()

'/home/nando/PycharmProjects/binpan_studio_dev/last_plot.png'

In [12]:
sym.get_orderbook()
sym.plot_orderbook_density()

'/home/nando/PycharmProjects/binpan_studio_dev/last_plot.png'

By combining candlestick data, technical indicators, trade flow analysis (atomic trades), volume profiling (market profile), support/resistance levels, and order book density, you can build a more complete picture of the market microstructure to inform trading decisions.

---

For more examples, see the other notebooks in this repository: trading indicators, plotting, exchange operations, and database integration.