In [2]:
!python -V

Python 3.11.2

In [3]:
import binpan
binpan.__version__

'0.8.14'

# Create a Symbol Instance

The `Symbol` class is the main entry point in BinPan. It fetches candlestick (kline) data from the Binance API for a given trading pair and timeframe. The resulting DataFrame contains OHLCV data plus metadata like timestamps and taker volumes.

Key parameters:
- `symbol`: the trading pair (e.g. `"LTCBTC"`)
- `tick_interval`: candle timeframe (`"1m"`, `"5m"`, `"1h"`, `"1d"`, etc.)
- `time_zone`: display timezone for the index
- `limit`: number of candles to fetch

In [4]:
symbol = "LTCBTC"
tick_interval = "1m"

In [5]:
sym = binpan.Symbol(symbol=symbol, tick_interval=tick_interval, time_zone="Europe/Madrid", limit = 500)
sym.df

2026-03-04	 21:36:14     INFO get_candles_by_time_stamps -> symbol=LTCBTC tick_interval=1m start=2026-03-04 13:15:00 end=2026-03-04 21:35:59 limit=500
2026-03-04	 21:36:15     INFO Rate limits obtenidos de Binance API

                                          Open time      Open      High       Low     Close  Volume                       Close time  Quote volume  Trades  Taker buy base volume  Taker buy quote volume  Ignore  Open timestamp  Close timestamp
LTCBTC 1m Europe/Madrid
2026-03-04 13:15:00+01:00 2026-03-04 13:15:00+01:00  0.000785  0.000785  0.000785  0.000785   0.000 2026-03-04 13:15:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772626500000    1772626559999
2026-03-04 13:16:00+01:00 2026-03-04 13:16:00+01:00  0.000785  0.000785  0.000785  0.000785   1.664 2026-03-04 13:16:59.999000+01:00      0.001306       1                  0.000                0.000000       0   1772626560000    1772626619999
2026-03-04 13:17:00+01:00 2026-03-04 13:17:00+01:00  0.000785  0.000785  0.000785  0.000785   0.000 2026-03-04 13:17:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772626620000    1772626679999
2026-03-04 13:18:00+01:00 2026-03-04 13:18:00+01:00  0.000785  0.000785  0.000785  0.000785   3.724 2026-03-04 13:18:59.999000+01:00      0.002923       2                  0.000                0.000000       0   1772626680000    1772626739999
2026-03-04 13:19:00+01:00 2026-03-04 13:19:00+01:00  0.000785  0.000785  0.000785  0.000785   0.000 2026-03-04 13:19:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772626740000    1772626799999
...                                             ...       ...       ...       ...       ...     ...                              ...           ...     ...                    ...                     ...     ...             ...              ...
2026-03-04 21:30:00+01:00 2026-03-04 21:30:00+01:00  0.000780  0.000780  0.000780  0.000780   0.000 2026-03-04 21:30:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772656200000    1772656259999
2026-03-04 21:31:00+01:00 2026-03-04 21:31:00+01:00  0.000780  0.000780  0.000780  0.000780   0.000 2026-03-04 21:31:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772656260000    1772656319999
2026-03-04 21:32:00+01:00 2026-03-04 21:32:00+01:00  0.000781  0.000781  0.000781  0.000781   5.647 2026-03-04 21:32:59.999000+01:00      0.004410       2                  4.129                0.003225       0   1772656320000    1772656379999
2026-03-04 21:33:00+01:00 2026-03-04 21:33:00+01:00  0.000781  0.000781  0.000781  0.000781   1.947 2026-03-04 21:33:59.999000+01:00      0.001521       2                  1.947                0.001521       0   1772656380000    1772656439999
2026-03-04 21:34:00+01:00 2026-03-04 21:34:00+01:00  0.000781  0.000781  0.000781  0.000781   0.000 2026-03-04 21:34:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772656440000    1772656499999

[500 rows x 14 columns]

# Add Technical Indicators

BinPan provides built-in technical indicators that are added as new columns to the Symbol's DataFrame. Here we add:
- **EMA (Exponential Moving Average)**: a trend-following indicator with a 200-period window.
- **VWAP (Volume-Weighted Average Price)**: cumulative over the data range, it shows the average price weighted by volume and is commonly used as a reference for fair value.

Indicators added with `inplace=True` (the default) are automatically included in subsequent `sym.plot()` calls.

In [6]:
sym.ema(200)
sym.vwap()

2026-03-04	 21:36:19     INFO New column: EMA_200
2026-03-04	 21:36:22     INFO New column: VWAP_D

LTCBTC 1m Europe/Madrid
2026-03-04 13:15:00+01:00         NaN
2026-03-04 13:16:00+01:00    0.000785
2026-03-04 13:17:00+01:00    0.000785
2026-03-04 13:18:00+01:00    0.000785
2026-03-04 13:19:00+01:00    0.000785
                               ...
2026-03-04 21:30:00+01:00    0.000779
2026-03-04 21:31:00+01:00    0.000779
2026-03-04 21:32:00+01:00    0.000779
2026-03-04 21:33:00+01:00    0.000779
2026-03-04 21:34:00+01:00    0.000779
Name: VWAP_D, Length: 500, dtype: float64

In [7]:
sym.plot()

'C:\\Users\\ffad\\Pycharm_Projects\\binpan_studio\\last_plot.png'

# Atomic Trades Analysis

Atomic trades are the individual (non-aggregated) trades that occurred during the kline period. By fetching them, we can analyze the actual trade sizes and identify large buyers or sellers.

The `plot_atomic_trades_size()` method renders a bubble chart where bubble size represents trade quantity, allowing visual identification of significant market participants.

In [8]:
sym.get_atomic_trades()

2026-03-04	 21:36:29     INFO Obteniendo atomic trades de LTCBTC por tiempo: 2026-03-04 12:15:00.000000 -> 2026-03-04 20:34:00.000000

Requesting atomic trades between 2026-03-04 13:15:00 and 2026-03-04 21:34:00

2026-03-04	 21:36:30     INFO Rango de IDs atómicos descubierto para LTCBTC: 106784581 -> 106788008 (estimado 3428 trades)
2026-03-04	 21:36:32     INFO Peticiones API atomic trades LTCBTC: 1 (ID actual: 106785581)
2026-03-04	 21:36:33     INFO Peticiones API atomic trades LTCBTC: 2 (ID actual: 106786581)
2026-03-04	 21:36:33     INFO Peticiones API atomic trades LTCBTC: 3 (ID actual: 106787581)
2026-03-04	 21:36:33     INFO Peticiones API atomic trades LTCBTC: 4 (ID actual: 106788013)
2026-03-04	 21:36:33     INFO Atomic trades LTCBTC: 4 peticiones, 3432 trades obtenidos

                       Trade Id     Price  Quantity  Quote quantity                 Date      Timestamp  Buyer was maker  Best price match
LTCBTC Europe/Madrid
0                     106784581  0.000785     1.664        0.001306  2026-03-04 13:16:47  1772626607140             True              True
1                     106784582  0.000785     1.518        0.001192  2026-03-04 13:18:10  1772626690834             True              True
2                     106784583  0.000785     2.206        0.001732  2026-03-04 13:18:10  1772626690834             True              True
3                     106784584  0.000785     0.937        0.000736  2026-03-04 13:20:42  1772626842475            False              True
4                     106784585  0.000785     1.518        0.001192  2026-03-04 13:22:54  1772626974788            False              True
...                         ...       ...       ...             ...                  ...            ...              ...               ...
3423                  106788004  0.000780    10.864        0.008474  2026-03-04 21:26:21  1772655981737             True              True
3424                  106788005  0.000781     1.518        0.001186  2026-03-04 21:32:29  1772656349238             True              True
3425                  106788006  0.000781     4.129        0.003225  2026-03-04 21:32:38  1772656358017            False              True
3426                  106788007  0.000781     0.525        0.000410  2026-03-04 21:33:06  1772656386617            False              True
3427                  106788008  0.000781     1.422        0.001111  2026-03-04 21:33:08  1772656388305            False              True

[3428 rows x 8 columns]

In [9]:
sym.plot_atomic_trades_size(logarithmic=True, max_size=40)

'C:\\Users\\ffad\\Pycharm_Projects\\binpan_studio\\last_plot.png'

In the chart above, each trade is represented as a bubble whose size corresponds to the trade quantity. Color distinguishes taker buyers from taker sellers. The relationship between bubble size and price action reveals:
- **Exhaustion**: large taker buy volume without a corresponding price increase suggests buyer exhaustion.
- **Strength**: large taker buy volume followed by a price increase indicates strong buying pressure.
- **Hidden activity**: sometimes large taker buy entries are actually stop-loss executions or cancellations from the makers' side.

## Market Profile

The market profile aggregates volume at each price level, showing where the most trading activity occurred. This helps identify high-volume nodes (areas of price acceptance) and low-volume nodes (areas of price rejection).

In [10]:
sym.plot_market_profile(from_atomic_trades=True)

'C:\\Users\\ffad\\Pycharm_Projects\\binpan_studio\\last_plot.png'

# Support and Resistance Levels

BinPan uses K-Means clustering on trade data to identify price levels where significant volume has accumulated. These levels often act as support or resistance zones.

The `support_resistance()` method returns lists of support and resistance price centroids (the center of each cluster, representing the most representative price for that zone). When `from_atomic=True`, it uses the granular atomic trade data for more precise level detection.

In [11]:
sym.support_resistance(from_atomic=True)

2026-03-04	 21:36:40  WARNING Clustering data...
2026-03-04	 21:36:40     INFO Updating support_resistance levels for LTCBTC from atomic trades

([0.0007731992528019925,
  0.0007760160462130936,
  0.0007792045,
  0.0007821700493691717,
  0.0007847859237536658],
 [])

Once support and resistance levels are computed, they are automatically overlaid on the candlestick chart when calling `sym.plot()`. The horizontal lines mark the cluster centroids where the highest trade volume concentration was detected.

## Order Book Density

The order book snapshot shows the current distribution of limit orders (bids and asks) at different price levels, providing insight into near-term supply and demand zones.

In [12]:
sym.plot()

'C:\\Users\\ffad\\Pycharm_Projects\\binpan_studio\\last_plot.png'

In [13]:
sym.get_orderbook()
sym.plot_orderbook_density()

'C:\\Users\\ffad\\Pycharm_Projects\\binpan_studio\\last_plot.png'

By combining candlestick data, technical indicators, trade flow analysis (atomic trades), volume profiling (market profile), support/resistance levels, and order book density, you can build a more complete picture of the market microstructure to inform trading decisions.

---

For more examples, see the other notebooks in this repository: trading indicators, plotting, exchange operations, and database integration.