# Welcome to BinPan's Basic Tutorial

Some API calls require an API key -- endpoints like the wallet, orders, etc.

BinPan contains no Binance **order method, withdraw method** or any dangerous command.

If you decide to add API keys for using account methods, BinPan will encrypt them in a file and in memory,
but it is recommended not to enable trading capability in the Binance API key configuration, just for your own peace of mind.

Be careful out there!

In [1]:
import binpan

You can add `api_key` and `api_secret` to get more from the API. They are needed to use the Wallet and Exchange classes.

In [2]:
!python -V

Python 3.13.12

In [3]:
binpan.__version__

'0.8.14'

# Get data

Select a symbol, a tick interval, and a time interval -- or just a limit of candles.

Time interval inputs can be a string like `2022-02-14 12:00:00`.

In [4]:
# Fetch the last 200 candles for LTCBTC, 1-minute interval
lun = binpan.Symbol(symbol='LTCUSDT',
                    tick_interval='1m',
                    limit=200,
                    time_zone='Europe/Madrid',
                    closed=True)
lun.df

2026-03-05	 20:29:05     INFO get_candles_by_time_stamps -> symbol=LTCUSDT tick_interval=1m start=2026-03-05 17:08:00 end=2026-03-05 20:28:59 limit=200
2026-03-05 20:29:05     INFO [panzer.binance.public.spot] Inicializando BinancePublicClient(market=spot)
2026-03-05 20:29:06     INFO [panzer.binance.public.spot] Rate limiter inicializado: max_per_minute=6000 safety_ratio=0.90

                                          Open time   Open   High    Low  Close    Volume                       Close time  Quote volume  Trades  Taker buy base volume  Taker buy quote volume  Ignore  Open timestamp  Close timestamp
LTCUSDT 1m Europe/Madrid
2026-03-05 17:08:00+01:00 2026-03-05 17:08:00+01:00  55.33  55.33  55.19  55.26  1428.294 2026-03-05 17:08:59.999000+01:00   78924.55342     717                360.444             19921.41882       0   1772726880000    1772726939999
2026-03-05 17:09:00+01:00 2026-03-05 17:09:00+01:00  55.25  55.25  55.10  55.11  1063.271 2026-03-05 17:09:59.999000+01:00   58667.36836     640                293.285             16181.92976       0   1772726940000    1772726999999
2026-03-05 17:10:00+01:00 2026-03-05 17:10:00+01:00  55.10  55.13  55.07  55.08   780.942 2026-03-05 17:10:59.999000+01:00   43032.67640     563                325.174             17917.47697       0   1772727000000    1772727059999
2026-03-05 17:11:00+01:00 2026-03-05 17:11:00+01:00  55.09  55.12  55.05  55.12  1197.672 2026-03-05 17:11:59.999000+01:00   65963.19627     430                275.657             15184.00087       0   1772727060000    1772727119999
2026-03-05 17:12:00+01:00 2026-03-05 17:12:00+01:00  55.12  55.17  55.08  55.17   999.668 2026-03-05 17:12:59.999000+01:00   55103.38092     480                460.365             25377.89520       0   1772727120000    1772727179999
...                                             ...    ...    ...    ...    ...       ...                              ...           ...     ...                    ...                     ...     ...             ...              ...
2026-03-05 20:23:00+01:00 2026-03-05 20:23:00+01:00  55.79  55.82  55.76  55.80   264.622 2026-03-05 20:23:59.999000+01:00   14761.21909     168                135.947              7583.54839       0   1772738580000    1772738639999
2026-03-05 20:24:00+01:00 2026-03-05 20:24:00+01:00  55.79  55.82  55.76  55.80  1398.503 2026-03-05 20:24:59.999000+01:00   78024.68646     328               1033.585             57667.84463       0   1772738640000    1772738699999
2026-03-05 20:25:00+01:00 2026-03-05 20:25:00+01:00  55.80  55.80  55.71  55.73   181.510 2026-03-05 20:25:59.999000+01:00   10117.67518     149                 57.138              3184.66682       0   1772738700000    1772738759999
2026-03-05 20:26:00+01:00 2026-03-05 20:26:00+01:00  55.74  55.75  55.69  55.71   375.740 2026-03-05 20:26:59.999000+01:00   20933.61895     174                 35.034              1952.46028       0   1772738760000    1772738819999
2026-03-05 20:27:00+01:00 2026-03-05 20:27:00+01:00  55.71  55.71  55.61  55.62   757.621 2026-03-05 20:27:59.999000+01:00   42175.35224     187                 16.161               899.64790       0   1772738820000    1772738879999

[200 rows x 14 columns]

In [5]:
list(lun.df.columns)

['Open time',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'Close time',
 'Quote volume',
 'Trades',
 'Taker buy base volume',
 'Taker buy quote volume',
 'Ignore',
 'Open timestamp',
 'Close timestamp']

# Indicators

Another Jupyter Notebook is available with more examples about indicators.

Let's add some technical indicators.

In [6]:
# Check and repair any gaps in the kline data
lun.repair_continuity()

2026-03-05	 20:29:07     INFO Repairing kline discontinuity with selective ffill...
2026-03-05	 20:29:07     INFO Common interval found: 60000 ms. Inserting 0 missing rows...
2026-03-05	 20:29:07     INFO Filling missing values...
2026-03-05	 20:29:07     INFO Klines continuity verification after repair
2026-03-05	 20:29:07     INFO Klines continuity OK

## Repair kline discontinuity

If kline data has gaps (e.g. from the exchange not returning certain candles), `repair_continuity()` will fill them with the previous candle's Close value.

In [7]:
lun.ema(21)

2026-03-05	 20:29:08     INFO New column: EMA_21

LTCUSDT 1m Europe/Madrid
2026-03-05 17:08:00+01:00    55.260000
2026-03-05 17:09:00+01:00    55.246364
2026-03-05 17:10:00+01:00    55.231240
2026-03-05 17:11:00+01:00    55.221127
2026-03-05 17:12:00+01:00    55.216479
                               ...
2026-03-05 20:23:00+01:00    55.703821
2026-03-05 20:24:00+01:00    55.712565
2026-03-05 20:25:00+01:00    55.714150
2026-03-05 20:26:00+01:00    55.713773
2026-03-05 20:27:00+01:00    55.705248
Name: EMA_21, Length: 200, dtype: float64

In [8]:
lun.supertrend()

2026-03-05	 20:29:09     INFO New column: SUPERT_10_3
2026-03-05	 20:29:09     INFO New column: SUPERTd_10_3
2026-03-05	 20:29:09     INFO New column: SUPERTl_10_3
2026-03-05	 20:29:09     INFO New column: SUPERTs_10_3

                           SUPERT_10_3  SUPERTd_10_3  SUPERTl_10_3  SUPERTs_10_3
LTCUSDT 1m Europe/Madrid
2026-03-05 17:08:00+01:00    54.840000           1.0     54.840000           NaN
2026-03-05 17:09:00+01:00    54.840000           1.0     54.840000           NaN
2026-03-05 17:10:00+01:00    54.840000           1.0     54.840000           NaN
2026-03-05 17:11:00+01:00    54.840000           1.0     54.840000           NaN
2026-03-05 17:12:00+01:00    54.840000           1.0     54.840000           NaN
...                                ...           ...           ...           ...
2026-03-05 20:23:00+01:00    55.668999           1.0     55.668999           NaN
2026-03-05 20:24:00+01:00    55.668999           1.0     55.668999           NaN
2026-03-05 20:25:00+01:00    55.668999           1.0     55.668999           NaN
2026-03-05 20:26:00+01:00    55.668999           1.0     55.668999           NaN
2026-03-05 20:27:00+01:00    55.850015          -1.0           NaN     55.850015

[200 rows x 4 columns]

By default, technical indicators are added to the instance with the argument `inplace=True`.

In [9]:
lun.df

                                          Open time   Open   High    Low  Close    Volume                       Close time  Quote volume  Trades  Taker buy base volume  Taker buy quote volume  Ignore  Open timestamp  Close timestamp     EMA_21  SUPERT_10_3  SUPERTd_10_3  SUPERTl_10_3  SUPERTs_10_3
LTCUSDT 1m Europe/Madrid
2026-03-05 17:08:00+01:00 2026-03-05 17:08:00+01:00  55.33  55.33  55.19  55.26  1428.294 2026-03-05 17:08:59.999000+01:00   78924.55342     717                360.444             19921.41882       0    1.772727e+12     1.772727e+12  55.260000    54.840000           1.0     54.840000           NaN
2026-03-05 17:09:00+01:00 2026-03-05 17:09:00+01:00  55.25  55.25  55.10  55.11  1063.271 2026-03-05 17:09:59.999000+01:00   58667.36836     640                293.285             16181.92976       0    1.772727e+12     1.772727e+12  55.246364    54.840000           1.0     54.840000           NaN
2026-03-05 17:10:00+01:00 2026-03-05 17:10:00+01:00  55.10  55.13  55.07  55.08   780.942 2026-03-05 17:10:59.999000+01:00   43032.67640     563                325.174             17917.47697       0    1.772727e+12     1.772727e+12  55.231240    54.840000           1.0     54.840000           NaN
2026-03-05 17:11:00+01:00 2026-03-05 17:11:00+01:00  55.09  55.12  55.05  55.12  1197.672 2026-03-05 17:11:59.999000+01:00   65963.19627     430                275.657             15184.00087       0    1.772727e+12     1.772727e+12  55.221127    54.840000           1.0     54.840000           NaN
2026-03-05 17:12:00+01:00 2026-03-05 17:12:00+01:00  55.12  55.17  55.08  55.17   999.668 2026-03-05 17:12:59.999000+01:00   55103.38092     480                460.365             25377.89520       0    1.772727e+12     1.772727e+12  55.216479    54.840000           1.0     54.840000           NaN
...                                             ...    ...    ...    ...    ...       ...                              ...           ...     ...                    ...                     ...     ...             ...              ...        ...          ...           ...           ...           ...
2026-03-05 20:23:00+01:00 2026-03-05 20:23:00+01:00  55.79  55.82  55.76  55.80   264.622 2026-03-05 20:23:59.999000+01:00   14761.21909     168                135.947              7583.54839       0    1.772739e+12     1.772739e+12  55.703821    55.668999           1.0     55.668999           NaN
2026-03-05 20:24:00+01:00 2026-03-05 20:24:00+01:00  55.79  55.82  55.76  55.80  1398.503 2026-03-05 20:24:59.999000+01:00   78024.68646     328               1033.585             57667.84463       0    1.772739e+12     1.772739e+12  55.712565    55.668999           1.0     55.668999           NaN
2026-03-05 20:25:00+01:00 2026-03-05 20:25:00+01:00  55.80  55.80  55.71  55.73   181.510 2026-03-05 20:25:59.999000+01:00   10117.67518     149                 57.138              3184.66682       0    1.772739e+12     1.772739e+12  55.714150    55.668999           1.0     55.668999           NaN
2026-03-05 20:26:00+01:00 2026-03-05 20:26:00+01:00  55.74  55.75  55.69  55.71   375.740 2026-03-05 20:26:59.999000+01:00   20933.61895     174                 35.034              1952.46028       0    1.772739e+12     1.772739e+12  55.713773    55.668999           1.0     55.668999           NaN
2026-03-05 20:27:00+01:00 2026-03-05 20:27:00+01:00  55.71  55.71  55.61  55.62   757.621 2026-03-05 20:27:59.999000+01:00   42175.35224     187                 16.161               899.64790       0    1.772739e+12     1.772739e+12  55.705248    55.850015          -1.0           NaN     55.850015

[200 rows x 19 columns]

# Plots

Another Jupyter Notebook is available with more examples about plotting.

These are the very basics.

In [10]:
lun.plot()

'/home/nando/PycharmProjects/binpan_studio_dev/notebooks/last_plot.png'

# Trades

Trades can be downloaded for the time period of the instance.

**Beware of requesting large time periods.**

BinPan monitors the API weight and waits if it is approaching the limit.

In [11]:
lun.get_atomic_trades()

2026-03-05	 20:29:12     INFO Obteniendo atomic trades de LTCUSDT por tiempo: 2026-03-05 16:08:00.000000 -> 2026-03-05 19:27:00.000000

Requesting atomic trades between 2026-03-05 17:08:00 and 2026-03-05 20:27:00

2026-03-05	 20:29:13     INFO Rango de IDs atómicos descubierto para LTCUSDT: 566622404 -> 566659015 (estimado 36612 trades)
2026-03-05	 20:29:14     INFO Peticiones API atomic trades LTCUSDT: 1 (ID actual: 566623404)
2026-03-05	 20:29:15     INFO Peticiones API atomic trades LTCUSDT: 2 (ID actual: 566624404)
2026-03-05	 20:29:15     INFO Peticiones API atomic trades LTCUSDT: 3 (ID actual: 566625404)
2026-03-05	 20:29:15     INFO Peticiones API atomic trades LTCUSDT: 4 (ID actual: 566626404)
2026-03-05	 20:29:15     INFO Peticiones API atomic trades LTCUSDT: 5 (ID actual: 566627404)
2026-03-05	 20:29:16     INFO Peticiones API atomic trades LTCUSDT: 6 (ID actual: 566628404)
2026-03-05	 20:29:16     INFO Peticiones API atomic trades LTCUSDT: 7 (ID actual: 566629404)
2026-03-05	 20:29:16     INFO Peticiones API atomic trades LTCUSDT: 8 (ID actual: 566630404)
2026-03-05	 20:29:16     INFO Peticiones API atomic trades LTCUSDT: 9 (ID actual: 566631404)
2026-03-05	 20:29:17     INFO Peticiones API atomic trades LTCUSDT: 10 (ID actual: 566632404)
2026-03-05	 20:29:17     INFO Peticiones API atomic trades LTCUSDT: 11 (ID actual: 566633404)
2026-03-05	 20:29:17     INFO Peticiones API atomic trades LTCUSDT: 12 (ID actual: 566634404)
2026-03-05	 20:29:18     INFO Peticiones API atomic trades LTCUSDT: 13 (ID actual: 566635404)
2026-03-05	 20:29:18     INFO Peticiones API atomic trades LTCUSDT: 14 (ID actual: 566636404)
2026-03-05	 20:29:18     INFO Peticiones API atomic trades LTCUSDT: 15 (ID actual: 566637404)
2026-03-05	 20:29:18     INFO Peticiones API atomic trades LTCUSDT: 16 (ID actual: 566638404)
2026-03-05	 20:29:19     INFO Peticiones API atomic trades LTCUSDT: 17 (ID actual: 566639404)
2026-03-05	 20:29:19     INFO Peticiones API atomic trades LTCUSDT: 18 (ID actual: 566640404)
2026-03-05	 20:29:19     INFO Peticiones API atomic trades LTCUSDT: 19 (ID actual: 566641404)
2026-03-05	 20:29:19     INFO Peticiones API atomic trades LTCUSDT: 20 (ID actual: 566642404)
2026-03-05	 20:29:20     INFO Peticiones API atomic trades LTCUSDT: 21 (ID actual: 566643404)
2026-03-05	 20:29:20     INFO Peticiones API atomic trades LTCUSDT: 22 (ID actual: 566644404)
2026-03-05	 20:29:20     INFO Peticiones API atomic trades LTCUSDT: 23 (ID actual: 566645404)
2026-03-05	 20:29:20     INFO Peticiones API atomic trades LTCUSDT: 24 (ID actual: 566646404)
2026-03-05	 20:29:21     INFO Peticiones API atomic trades LTCUSDT: 25 (ID actual: 566647404)
2026-03-05	 20:29:21     INFO Peticiones API atomic trades LTCUSDT: 26 (ID actual: 566648404)
2026-03-05	 20:29:21     INFO Peticiones API atomic trades LTCUSDT: 27 (ID actual: 566649404)
2026-03-05	 20:29:21     INFO Peticiones API atomic trades LTCUSDT: 28 (ID actual: 566650404)
2026-03-05	 20:29:22     INFO Peticiones API atomic trades LTCUSDT: 29 (ID actual: 566651404)
2026-03-05	 20:29:22     INFO Peticiones API atomic trades LTCUSDT: 30 (ID actual: 566652404)
2026-03-05	 20:29:22     INFO Peticiones API atomic trades LTCUSDT: 31 (ID actual: 566653404)
2026-03-05	 20:29:23     INFO Peticiones API atomic trades LTCUSDT: 32 (ID actual: 566654404)
2026-03-05	 20:29:23     INFO Peticiones API atomic trades LTCUSDT: 33 (ID actual: 566655404)
2026-03-05	 20:29:23     INFO Peticiones API atomic trades LTCUSDT: 34 (ID actual: 566656404)
2026-03-05	 20:29:23     INFO Peticiones API atomic trades LTCUSDT: 35 (ID actual: 566657404)
2026-03-05	 20:29:24     INFO Peticiones API atomic trades LTCUSDT: 36 (ID actual: 566658404)
2026-03-05	 20:29:24     INFO Peticiones API atomic trades LTCUSDT: 37 (ID actual: 566659404)
2026-03-05	 20:29:24     INFO Atomic trades LTCUSDT: 37 peticiones, 37000 trades obtenidos

                        Trade Id  Price  Quantity  Quote quantity                 Date      Timestamp  Buyer was maker  Best price match
LTCUSDT Europe/Madrid
0                      566622404  55.33     0.095         5.25635  2026-03-05 17:08:00  1772726880033            False              True
1                      566622405  55.33     0.095         5.25635  2026-03-05 17:08:00  1772726880033            False              True
2                      566622406  55.33     2.071       114.58843  2026-03-05 17:08:00  1772726880033            False              True
3                      566622407  55.32     0.181        10.01292  2026-03-05 17:08:01  1772726881409             True              True
4                      566622408  55.32     0.100         5.53200  2026-03-05 17:08:01  1772726881409             True              True
...                          ...    ...       ...             ...                  ...            ...              ...               ...
36995                  566659399  55.43     0.095         5.26585  2026-03-05 19:48:36  1772736516660            False              True
36996                  566659400  55.43     0.095         5.26585  2026-03-05 19:48:36  1772736516660            False              True
36997                  566659401  55.43     0.693        38.41299  2026-03-05 19:48:36  1772736516660            False              True
36998                  566659402  55.43     0.224        12.41632  2026-03-05 19:48:36  1772736516660            False              True
36999                  566659403  55.43     1.450        80.37350  2026-03-05 19:48:36  1772736516660            False              True

[37000 rows x 8 columns]

In [12]:
lun.get_agg_trades(minutes=60)

2026-03-05	 20:29:24     INFO Obteniendo aggTrades de LTCUSDT por tiempo: 2026-03-05 18:29:24.746000 -> 2026-03-05 19:27:00.000000

Requesting aggregated trades between 2026-03-05 19:29:24 and 2026-03-05 20:27:00

2026-03-05	 20:29:25     INFO aggTrades LTCUSDT: 3 peticiones, 2757 trades obtenidos

                       Aggregate tradeId  Price  Quantity  First tradeId  Last tradeId                 Date      Timestamp  Buyer was maker  Best price match
LTCUSDT Europe/Madrid
0                              324305937  55.11     0.363      566655400     566655400  2026-03-05 19:29:25  1772735365676            False              True
1                              324305938  55.10     1.880      566655401     566655401  2026-03-05 19:29:28  1772735368975             True              True
2                              324305939  55.11     0.118      566655402     566655402  2026-03-05 19:29:31  1772735371563            False              True
3                              324305940  55.11     3.056      566655403     566655410  2026-03-05 19:29:33  1772735373832            False              True
4                              324305941  55.11     2.333      566655411     566655411  2026-03-05 19:29:33  1772735373834            False              True
...                                  ...    ...       ...            ...           ...                  ...            ...              ...               ...
2752                           324308689  55.69     1.841      566665762     566665770  2026-03-05 20:26:53  1772738813243             True              True
2753                           324308690  55.70     2.033      566665771     566665778  2026-03-05 20:26:53  1772738813739            False              True
2754                           324308691  55.71     1.653      566665779     566665789  2026-03-05 20:26:54  1772738814623            False              True
2755                           324308692  55.71     0.323      566665790     566665790  2026-03-05 20:26:55  1772738815510             True              True
2756                           324308693  55.71     0.700      566665791     566665791  2026-03-05 20:26:57  1772738817446             True              True

[2757 rows x 9 columns]

# Plots with trades

Using `plot_agg_trades_size()`, you can visualize the size of aggregated trades. Useful for finding whale operations or support/resistance levels.

In [13]:
lun.plot_agg_trades_size()

'/home/nando/PycharmProjects/binpan_studio_dev/notebooks/last_plot.png'

# Support and resistance levels with trades

In [14]:
lun.support_resistance(from_atomic=True, by_quantity=True)

2026-03-05	 20:29:27  WARNING Clustering data...
2026-03-05	 20:29:27     INFO Updating support_resistance levels for LTCUSDT from atomic trades

([55.141232448653945,
  55.29742182241123,
  55.44038709614507,
  55.607715338553305,
  55.75326002015953],
 [])

In [ ]:
lun.plot(title="LTCUSDT S/R desde atomic trades (alta precisión)")

# Fetching exchange data

There is a dedicated class called `Exchange` in BinPan for these tasks, but the `Symbol` class can also retrieve some exchange data.

In [16]:
lun.get_order_filters()

{'PRICE_FILTER_minPrice': '0.01000000',
 'PRICE_FILTER_maxPrice': '100000.00000000',
 'PRICE_FILTER_tickSize': '0.01000000',
 'LOT_SIZE_minQty': '0.00100000',
 'LOT_SIZE_maxQty': '90000.00000000',
 'LOT_SIZE_stepSize': '0.00100000',
 'ICEBERG_PARTS_limit': 50,
 'MARKET_LOT_SIZE_minQty': '0.00000000',
 'MARKET_LOT_SIZE_maxQty': '17019.15994142',
 'MARKET_LOT_SIZE_stepSize': '0.00000000',
 'TRAILING_DELTA_minTrailingAboveDelta': 10,
 'TRAILING_DELTA_maxTrailingAboveDelta': 2000,
 'TRAILING_DELTA_minTrailingBelowDelta': 10,
 'TRAILING_DELTA_maxTrailingBelowDelta': 2000,
 'PERCENT_PRICE_BY_SIDE_bidMultiplierUp': '2',
 'PERCENT_PRICE_BY_SIDE_bidMultiplierDown': '0.5',
 'PERCENT_PRICE_BY_SIDE_askMultiplierUp': '2',
 'PERCENT_PRICE_BY_SIDE_askMultiplierDown': '0.5',
 'PERCENT_PRICE_BY_SIDE_avgPriceMins': 5,
 'NOTIONAL_minNotional': '5.00000000',
 'NOTIONAL_applyMinToMarket': True,
 'NOTIONAL_maxNotional': '9000000.00000000',
 'NOTIONAL_applyMaxToMarket': False,
 'NOTIONAL_avgPriceMins': 5,
 'MAX_NUM_ORDERS_maxNumOrders': 200,
 'MAX_NUM_ORDER_LISTS_maxNumOrderLists': 20,
 'MAX_NUM_ALGO_ORDERS_maxNumAlgoOrders': 5,
 'MAX_NUM_ORDER_AMENDS_maxNumOrderAmends': 10}

In [17]:
lun.get_order_types()

['LIMIT',
 'LIMIT_MAKER',
 'MARKET',
 'STOP_LOSS',
 'STOP_LOSS_LIMIT',
 'TAKE_PROFIT',
 'TAKE_PROFIT_LIMIT']

In [18]:
lun.get_permissions()

['TRD_GRP_117',
 'TRD_GRP_121',
 'TRD_GRP_116',
 'TRD_GRP_150',
 'TRD_GRP_151',
 'TRD_GRP_112',
 'TRD_GRP_191',
 'TRD_GRP_198',
 'TRD_GRP_221',
 'TRD_GRP_023',
 'TRD_GRP_072',
 'TRD_GRP_127',
 'TRD_GRP_063',
 'TRD_GRP_075',
 'TRD_GRP_235',
 'TRD_GRP_233',
 'TRD_GRP_006',
 'TRD_GRP_056',
 'TRD_GRP_237',
 'TRD_GRP_082',
 'TRD_GRP_178',
 'TRD_GRP_004',
 'TRD_GRP_157',
 'TRD_GRP_092',
 'TRD_GRP_194',
 'TRD_GRP_242',
 'TRD_GRP_154',
 'TRD_GRP_182',
 'TRD_GRP_208',
 'TRD_GRP_107',
 'TRD_GRP_132',
 'TRD_GRP_083',
 'TRD_GRP_212',
 'TRD_GRP_070',
 'TRD_GRP_164',
 'TRD_GRP_220',
 'TRD_GRP_130',
 'TRD_GRP_218',
 'TRD_GRP_143',
 'TRD_GRP_202',
 'TRD_GRP_015',
 'TRD_GRP_098',
 'TRD_GRP_137',
 'TRD_GRP_090',
 'TRD_GRP_119',
 'TRD_GRP_149',
 'TRD_GRP_248',
 'TRD_GRP_018',
 'TRD_GRP_071',
 'TRD_GRP_133',
 'TRD_GRP_019',
 'TRD_GRP_086',
 'TRD_GRP_095',
 'TRD_GRP_232',
 'TRD_GRP_017',
 'TRD_GRP_251',
 'TRD_GRP_073',
 'SPOT',
 'TRD_GRP_126',
 'TRD_GRP_173',
 'TRD_GRP_060',
 'TRD_GRP_224',
 'TRD_GRP_168',
 'TRD_GRP_138',
 'TRD_GRP_180',
 'TRD_GRP_094',
 'TRD_GRP_093',
 'TRD_GRP_089',
 'TRD_GRP_244',
 'TRD_GRP_190',
 'TRD_GRP_222',
 'TRD_GRP_204',
 'TRD_GRP_252',
 'TRD_GRP_210',
 'TRD_GRP_069',
 'TRD_GRP_099',
 'TRD_GRP_160',
 'TRD_GRP_174',
 'TRD_GRP_197',
 'TRD_GRP_245',
 'TRD_GRP_169',
 'TRD_GRP_147',
 'TRD_GRP_200',
 'TRD_GRP_205',
 'TRD_GRP_049',
 'TRD_GRP_059',
 'TRD_GRP_172',
 'TRD_GRP_181',
 'TRD_GRP_152',
 'TRD_GRP_068',
 'TRD_GRP_052',
 'TRD_GRP_135',
 'TRD_GRP_021',
 'TRD_GRP_114',
 'TRD_GRP_118',
 'TRD_GRP_238',
 'TRD_GRP_084',
 'TRD_GRP_196',
 'TRD_GRP_186',
 'TRD_GRP_189',
 'TRD_GRP_055',
 'TRD_GRP_187',
 'TRD_GRP_230',
 'TRD_GRP_163',
 'TRD_GRP_203',
 'TRD_GRP_195',
 'TRD_GRP_246',
 'TRD_GRP_153',
 'TRD_GRP_124',
 'TRD_GRP_148',
 'TRD_GRP_216',
 'TRD_GRP_225',
 'TRD_GRP_077',
 'TRD_GRP_144',
 'TRD_GRP_184',
 'TRD_GRP_087',
 'TRD_GRP_131',
 'TRD_GRP_062',
 'TRD_GRP_058',
 'TRD_GRP_053',
 'TRD_GRP_199',
 'TRD_GRP_243',
 'TRD_GRP_156',
 'TRD_GRP_102',
 'TRD_GRP_088',
 'TRD_GRP_080',
 'TRD_GRP_109',
 'TRD_GRP_110',
 'TRD_GRP_129',
 'TRD_GRP_120',
 'TRD_GRP_061',
 'TRD_GRP_240',
 'TRD_GRP_081',
 'TRD_GRP_091',
 'TRD_GRP_096',
 'TRD_GRP_076',
 'TRD_GRP_122',
 'TRD_GRP_141',
 'TRD_GRP_192',
 'TRD_GRP_239',
 'TRD_GRP_253',
 'TRD_GRP_166',
 'TRD_GRP_067',
 'TRD_GRP_101',
 'TRD_GRP_064',
 'TRD_GRP_106',
 'TRD_GRP_250',
 'TRD_GRP_020',
 'TRD_GRP_054',
 'TRD_GRP_231',
 'TRD_GRP_165',
 'TRD_GRP_115',
 'TRD_GRP_188',
 'TRD_GRP_145',
 'TRD_GRP_134',
 'TRD_GRP_211',
 'TRD_GRP_066',
 'TRD_GRP_229',
 'TRD_GRP_078',
 'TRD_GRP_113',
 'TRD_GRP_167',
 'TRD_GRP_111',
 'TRD_GRP_051',
 'TRD_GRP_179',
 'TRD_GRP_050',
 'TRD_GRP_065',
 'TRD_GRP_146',
 'TRD_GRP_201',
 'TRD_GRP_206',
 'TRD_GRP_108',
 'TRD_GRP_177',
 'TRD_GRP_227',
 'TRD_GRP_249',
 'TRD_GRP_161',
 'TRD_GRP_158',
 'TRD_GRP_219',
 'TRD_GRP_185',
 'TRD_GRP_022',
 'TRD_GRP_223',
 'TRD_GRP_025',
 'TRD_GRP_016',
 'TRD_GRP_100',
 'TRD_GRP_162',
 'TRD_GRP_085',
 'TRD_GRP_057',
 'TRD_GRP_171',
 'TRD_GRP_105',
 'TRD_GRP_125',
 'TRD_GRP_123',
 'TRD_GRP_214',
 'TRD_GRP_140',
 'TRD_GRP_139',
 'TRD_GRP_234',
 'TRD_GRP_193',
 'TRD_GRP_074',
 'TRD_GRP_170',
 'TRD_GRP_183',
 'TRD_GRP_247',
 'TRD_GRP_217',
 'TRD_GRP_175',
 'TRD_GRP_207',
 'TRD_GRP_136',
 'TRD_GRP_213',
 'TRD_GRP_228',
 'TRD_GRP_104',
 'TRD_GRP_024',
 'TRD_GRP_097',
 'TRD_GRP_236',
 'TRD_GRP_142',
 'TRD_GRP_215',
 'TRD_GRP_176',
 'TRD_GRP_155',
 'TRD_GRP_128',
 'MARGIN',
 'TRD_GRP_159',
 'TRD_GRP_209',
 'TRD_GRP_226',
 'TRD_GRP_079',
 'TRD_GRP_005',
 'TRD_GRP_103']

In [19]:
lun.get_precision()

{'baseAssetPrecision': 8,
 'quoteAssetPrecision': 8,
 'baseCommissionPrecision': 8,
 'quoteCommissionPrecision': 8}

# Other interesting data

## Market Profile

In [20]:
lun.plot_market_profile(from_atomic_trades=True)

'/home/nando/PycharmProjects/binpan_studio_dev/notebooks/last_plot.png'

## Resample klines

You can resample klines to a different (larger) timeframe. For instance, aggregate 1-minute candles into 5-minute candles.

In [21]:
lun.hk()

,Open time,Open,High,Low,Close,Volume,Close time,Quote volume,Trades,Taker buy base volume,Taker buy quote volume,Ignore,Open timestamp,Close timestamp,EMA_21,SUPERT_10_3,SUPERTd_10_3,SUPERTl_10_3,SUPERTs_10_3,Support_Resistance_1,Support_Resistance_2,Support_Resistance_3,Support_Resistance_4,Support_Resistance_5
LTCUSDT 1m Europe/Madrid HK,,,,,,,,,,,,,,,,,,,,,,,,
2026-03-05 17:08:00+01:00,2026-03-05 17:08:00+01:00,55.330000,55.330000,55.19,55.2775,1428.294,2026-03-05 17:08:59.999000+01:00,78924.55342,717,360.444,19921.41882,0,1.772727e+12,1.772727e+12,55.260000,54.840000,1.0,54.840000,NaN,55.141232,55.297422,55.440387,55.607715,55.75326
2026-03-05 17:09:00+01:00,2026-03-05 17:09:00+01:00,55.303750,55.303750,55.10,55.1775,1063.271,2026-03-05 17:09:59.999000+01:00,58667.36836,640,293.285,16181.92976,0,1.772727e+12,1.772727e+12,55.246364,54.840000,1.0,54.840000,NaN,55.141232,55.297422,55.440387,55.607715,55.75326
2026-03-05 17:10:00+01:00,2026-03-05 17:10:00+01:00,55.240625,55.240625,55.07,55.0950,780.942,2026-03-05 17:10:59.999000+01:00,43032.67640,563,325.174,17917.47697,0,1.772727e+12,1.772727e+12,55.231240,54.840000,1.0,54.840000,NaN,55.141232,55.297422,55.440387,55.607715,55.75326
2026-03-05 17:11:00+01:00,2026-03-05 17:11:00+01:00,55.167812,55.167812,55.05,55.0950,1197.672,2026-03-05 17:11:59.999000+01:00,65963.19627,430,275.657,15184.00087,0,1.772727e+12,1.772727e+12,55.221127,54.840000,1.0,54.840000,NaN,55.141232,55.297422,55.440387,55.607715,55.75326
2026-03-05 17:12:00+01:00,2026-03-05 17:12:00+01:00,55.131406,55.170000,55.08,55.1350,999.668,2026-03-05 17:12:59.999000+01:00,55103.38092,480,460.365,25377.89520,0,1.772727e+12,1.772727e+12,55.216479,54.840000,1.0,54.840000,NaN,55.141232,55.297422,55.440387,55.607715,55.75326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-03-05 20:23:00+01:00,2026-03-05 20:23:00+01:00,55.811887,55.820000,55.76,55.7925,264.622,2026-03-05 20:23:59.999000+01:00,14761.21909,168,135.947,7583.54839,0,1.772739e+12,1.772739e+12,55.703821,55.668999,1.0,55.668999,NaN,55.141232,55.297422,55.440387,55.607715,55.75326
2026-03-05 20:24:00+01:00,2026-03-05 20:24:00+01:00,55.802194,55.820000,55.76,55.7925,1398.503,2026-03-05 20:24:59.999000+01:00,78024.68646,328,1033.585,57667.84463,0,1.772739e+12,1.772739e+12,55.712565,55.668999,1.0,55.668999,NaN,55.141232,55.297422,55.440387,55.607715,55.75326
2026-03-05 20:25:00+01:00,2026-03-05 20:25:00+01:00,55.797347,55.800000,55.71,55.7600,181.510,2026-03-05 20:25:59.999000+01:00,10117.67518,149,57.138,3184.66682,0,1.772739e+12,1.772739e+12,55.714150,55.668999,1.0,55.668999,NaN,55.141232,55.297422,55.440387,55.607715,55.75326
2026-03-05 20:26:00+01:00,2026-03-05 20:26:00+01:00,55.778673,55.778673,55.69,55.7225,375.740,2026-03-05 20:26:59.999000+01:00,20933.61895,174,35.034,1952.46028,0,1.772739e+12,1.772739e+12,55.713773,55.668999,1.0,55.668999,NaN,55.141232,55.297422,55.440387,55.607715,55.75326
2026-03-05 20:27:00+01:00,2026-03-05 20:27:00+01:00,55.750587,55.750587,55.61,55.6625,757.621,2026-03-05 20:27:59.999000+01:00,42175.35224,187,16.161,899.64790,0,1.772739e+12,1.772739e+12,55.705248,55.850015,-1.0,NaN,55.850015,55.141232,55.297422,55.440387,55.607715,55.75326

## Drop indicators

You can remove all added indicator columns and reset the DataFrame to its original OHLCV state using `drop()`.

In [22]:
resampled = lun.resample('5m')
resampled

2026-03-05	 20:29:29     INFO Resampling LTCUSDT from 1m to 5m

                                          Open time   Open   High    Low  Close    Volume                       Close time  Quote volume  Trades  Taker buy base volume  Taker buy quote volume  Ignore  Open timestamp  Close timestamp
LTCUSDT 5m Europe/Madrid
2026-03-05 17:05:00+01:00 2026-03-05 17:08:00+01:00  55.33  55.33  55.10  55.11  2491.565 2026-03-05 17:09:59.999000+01:00  137591.92178    1357                653.729             36103.34858       0    1.772727e+12     1.772727e+12
2026-03-05 17:10:00+01:00 2026-03-05 17:10:00+01:00  55.10  55.40  55.05  55.30  4246.901 2026-03-05 17:14:59.999000+01:00  234276.77574    2535               1692.819             93432.92988       0    1.772727e+12     1.772727e+12
2026-03-05 17:15:00+01:00 2026-03-05 17:15:00+01:00  55.31  55.50  55.24  55.34  2943.372 2026-03-05 17:19:59.999000+01:00  162869.96624    2229               1021.256             56505.12567       0    1.772727e+12     1.772728e+12
2026-03-05 17:20:00+01:00 2026-03-05 17:20:00+01:00  55.34  55.50  55.23  55.48  2124.154 2026-03-05 17:24:59.999000+01:00  117594.69783    1574               1159.494             64192.09825       0    1.772728e+12     1.772728e+12
2026-03-05 17:25:00+01:00 2026-03-05 17:25:00+01:00  55.48  55.55  55.41  55.50  1893.081 2026-03-05 17:29:59.999000+01:00  105037.13925    1217                733.571             40706.17799       0    1.772728e+12     1.772728e+12
...                                             ...    ...    ...    ...    ...       ...                              ...           ...     ...                    ...                     ...     ...             ...              ...
2026-03-05 20:05:00+01:00 2026-03-05 20:05:00+01:00  55.55  55.68  55.55  55.67  1095.245 2026-03-05 20:09:59.999000+01:00   60891.52356     716                936.339             52052.30524       0    1.772738e+12     1.772738e+12
2026-03-05 20:10:00+01:00 2026-03-05 20:10:00+01:00  55.67  55.79  55.62  55.77  1654.890 2026-03-05 20:14:59.999000+01:00   92194.22832     984                908.584             50636.13314       0    1.772738e+12     1.772738e+12
2026-03-05 20:15:00+01:00 2026-03-05 20:15:00+01:00  55.77  55.79  55.66  55.79  1617.924 2026-03-05 20:19:59.999000+01:00   90208.59776     717               1239.414             69112.52573       0    1.772738e+12     1.772738e+12
2026-03-05 20:20:00+01:00 2026-03-05 20:20:00+01:00  55.79  55.91  55.76  55.80  2642.598 2026-03-05 20:24:59.999000+01:00  147492.03758    1253               1819.771            101571.05211       0    1.772738e+12     1.772739e+12
2026-03-05 20:25:00+01:00 2026-03-05 20:25:00+01:00  55.80  55.80  55.61  55.62  1314.871 2026-03-05 20:27:59.999000+01:00   73226.64637     510                108.333              6036.77500       0    1.772739e+12     1.772739e+12

[41 rows x 14 columns]

## Heikin-Ashi candles

BinPan can compute Heikin-Ashi candles from normal OHLCV data. These smooth out price action and make trends easier to identify.

In [23]:
lun.hk(inplace=True)
lun.plot()

'/home/nando/PycharmProjects/binpan_studio_dev/notebooks/last_plot.png'

### Thank you.

For more examples, see the other notebooks in this repository covering technical indicators, plotting, strategy backtesting, exchange operations, and database integration.

In [24]:
lun.drop()
list(lun.df.columns)

['Open time',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'Close time',
 'Quote volume',
 'Trades',
 'Taker buy base volume',
 'Taker buy quote volume',
 'Ignore',
 'Open timestamp',
 'Close timestamp',
 'EMA_21',
 'SUPERT_10_3',
 'SUPERTd_10_3',
 'SUPERTl_10_3',
 'SUPERTs_10_3',
 'Support_Resistance_1',
 'Support_Resistance_2',
 'Support_Resistance_3',
 'Support_Resistance_4',
 'Support_Resistance_5']