In [1]:
import binpan

# Export and Import CSV Data

BinPan allows you to save kline (candlestick) data, atomic trades, and aggregated trades to CSV files.
These files can later be re-imported to create a `Symbol` instance without making new API requests.

In [2]:
sym = binpan.Symbol(symbol="ltcbtc", tick_interval="1m")
sym.df

2026-03-05	 21:31:07     INFO get_candles_by_time_stamps -> symbol=LTCBTC tick_interval=1m start=2026-03-05 04:50:00 end=2026-03-05 21:30:59 limit=1000
2026-03-05 21:31:07     INFO [panzer.binance.public.spot] Inicializando BinancePublicClient(market=spot)
2026-03-05 21:31:08     INFO [panzer.binance.public.spot] Rate limiter inicializado: max_per_minute=6000 safety_ratio=0.90

                                          Open time      Open      High       Low     Close  Volume                       Close time  Quote volume  Trades  Taker buy base volume  Taker buy quote volume  Ignore  Open timestamp  Close timestamp
LTCBTC 1m Europe/Madrid
2026-03-05 04:50:00+01:00 2026-03-05 04:50:00+01:00  0.000779  0.000779  0.000779  0.000779   0.167 2026-03-05 04:50:59.999000+01:00      0.000130       1                  0.167                0.000130       0   1772682600000    1772682659999
2026-03-05 04:51:00+01:00 2026-03-05 04:51:00+01:00  0.000778  0.000778  0.000778  0.000778   0.380 2026-03-05 04:51:59.999000+01:00      0.000296       1                  0.000                0.000000       0   1772682660000    1772682719999
2026-03-05 04:52:00+01:00 2026-03-05 04:52:00+01:00  0.000778  0.000778  0.000778  0.000778   0.000 2026-03-05 04:52:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772682720000    1772682779999
2026-03-05 04:53:00+01:00 2026-03-05 04:53:00+01:00  0.000778  0.000778  0.000778  0.000778   0.000 2026-03-05 04:53:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772682780000    1772682839999
2026-03-05 04:54:00+01:00 2026-03-05 04:54:00+01:00  0.000778  0.000778  0.000778  0.000778   0.000 2026-03-05 04:54:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772682840000    1772682899999
...                                             ...       ...       ...       ...       ...     ...                              ...           ...     ...                    ...                     ...     ...             ...              ...
2026-03-05 21:26:00+01:00 2026-03-05 21:26:00+01:00  0.000783  0.000783  0.000783  0.000783   0.158 2026-03-05 21:26:59.999000+01:00      0.000124       1                  0.000                0.000000       0   1772742360000    1772742419999
2026-03-05 21:27:00+01:00 2026-03-05 21:27:00+01:00  0.000784  0.000784  0.000784  0.000784   4.577 2026-03-05 21:27:59.999000+01:00      0.003588       2                  0.000                0.000000       0   1772742420000    1772742479999
2026-03-05 21:28:00+01:00 2026-03-05 21:28:00+01:00  0.000784  0.000784  0.000784  0.000784   0.000 2026-03-05 21:28:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772742480000    1772742539999
2026-03-05 21:29:00+01:00 2026-03-05 21:29:00+01:00  0.000785  0.000785  0.000785  0.000785   5.593 2026-03-05 21:29:59.999000+01:00      0.004390       8                  5.593                0.004390       0   1772742540000    1772742599999
2026-03-05 21:30:00+01:00 2026-03-05 21:30:00+01:00  0.000785  0.000785  0.000785  0.000785   5.719 2026-03-05 21:30:59.999000+01:00      0.004489       4                  4.825                0.003788       0   1772742600000    1772742659999

[1001 rows x 14 columns]

In [3]:
sym.save_csv()

2026-03-05	 21:31:09     INFO Saved file LTCBTC 1m Europe-Madrid klines 1772682600000 1772742600000.csv

## Export Trades to CSV

Both atomic trades and aggregated trades can be exported with `save_atomic_trades_csv()` and `save_agg_trades_csv()` respectively.

In [4]:
sym.get_atomic_trades()

2026-03-05	 21:31:10     INFO Obteniendo atomic trades de LTCBTC por tiempo: 2026-03-05 03:50:00.000000 -> 2026-03-05 20:30:00.000000

Requesting atomic trades between 2026-03-05 04:50:00 and 2026-03-05 21:30:00

2026-03-05	 21:31:10     INFO Rango de IDs atómicos descubierto para LTCBTC: 106789049 -> 106791294 (estimado 2246 trades)
2026-03-05	 21:31:12     INFO Peticiones API atomic trades LTCBTC: 1 (ID actual: 106790049)
2026-03-05	 21:31:12     INFO Peticiones API atomic trades LTCBTC: 2 (ID actual: 106791049)
2026-03-05	 21:31:12     INFO Peticiones API atomic trades LTCBTC: 3 (ID actual: 106791299)
2026-03-05	 21:31:12     INFO Atomic trades LTCBTC: 3 peticiones, 2250 trades obtenidos

                       Trade Id     Price  Quantity  Quote quantity                 Date      Timestamp  Buyer was maker  Best price match
LTCBTC Europe/Madrid
0                     106789049  0.000779     0.167        0.000130  2026-03-05 04:50:43  1772682643379            False              True
1                     106789050  0.000778     0.380        0.000296  2026-03-05 04:51:46  1772682706571             True              True
2                     106789051  0.000779     0.358        0.000279  2026-03-05 04:59:57  1772683197800            False              True
3                     106789052  0.000779     0.272        0.000212  2026-03-05 05:00:05  1772683205571             True              True
4                     106789053  0.000778     0.879        0.000684  2026-03-05 05:00:13  1772683213741             True              True
...                         ...       ...       ...             ...                  ...            ...              ...               ...
2241                  106791290  0.000785     0.129        0.000101  2026-03-05 21:29:10  1772742550518            False              True
2242                  106791291  0.000785     1.518        0.001192  2026-03-05 21:29:10  1772742550518            False              True
2243                  106791292  0.000785     0.695        0.000546  2026-03-05 21:29:10  1772742550518            False              True
2244                  106791293  0.000785     0.179        0.000141  2026-03-05 21:29:11  1772742551087            False              True
2245                  106791294  0.000785     0.287        0.000225  2026-03-05 21:29:21  1772742561450            False              True

[2246 rows x 8 columns]

In [5]:
sym.save_atomic_trades_csv()

2026-03-05	 21:31:13     INFO Saved file LTCBTC Europe-Madrid atomicTrades 1772682600000 1772742600000.csv

In [6]:
sym.get_agg_trades()

2026-03-05	 21:31:13     INFO Obteniendo aggTrades de LTCBTC por tiempo: 2026-03-05 03:50:00.000000 -> 2026-03-05 20:30:00.000000

Requesting aggregated trades between 2026-03-05 04:50:00 and 2026-03-05 21:30:00

2026-03-05	 21:31:17     INFO aggTrades LTCBTC: 17 peticiones, 1633 trades obtenidos

                      Aggregate tradeId     Price  Quantity  First tradeId  Last tradeId                 Date      Timestamp  Buyer was maker  Best price match
LTCBTC Europe/Madrid
0                              81471983  0.000779     0.167      106789049     106789049  2026-03-05 04:50:43  1772682643379            False              True
1                              81471984  0.000778     0.380      106789050     106789050  2026-03-05 04:51:46  1772682706571             True              True
2                              81471985  0.000779     0.358      106789051     106789051  2026-03-05 04:59:57  1772683197800            False              True
3                              81471986  0.000779     0.272      106789052     106789052  2026-03-05 05:00:05  1772683205571             True              True
4                              81471987  0.000778     0.879      106789053     106789053  2026-03-05 05:00:13  1772683213741             True              True
...                                 ...       ...       ...            ...           ...                  ...            ...              ...               ...
1628                           81473611  0.000783     0.158      106791284     106791284  2026-03-05 21:26:21  1772742381450             True              True
1629                           81473612  0.000784     4.577      106791285     106791286  2026-03-05 21:27:09  1772742429537             True              True
1630                           81473613  0.000785     5.127      106791287     106791292  2026-03-05 21:29:10  1772742550518            False              True
1631                           81473614  0.000785     0.179      106791293     106791293  2026-03-05 21:29:11  1772742551087            False              True
1632                           81473615  0.000785     0.287      106791294     106791294  2026-03-05 21:29:21  1772742561450            False              True

[1633 rows x 9 columns]

In [7]:
sym.save_agg_trades_csv()

2026-03-05	 21:31:18     INFO Saved file LTCBTC Europe-Madrid aggTrades 1772682600000 1772742600000.csv

## Import Klines from CSV

Use `from_csv` with the filename to create a `Symbol` instance from a previously saved CSV file.
Passing `from_csv=True` (boolean) shows an interactive file selection menu — useful in console but
may not work in all Jupyter environments.

In [8]:
# Build the filename from the Symbol metadata (same pattern as save_csv)
start, end = sym.get_timestamps()
klines_csv = f"{sym.df.index.name.replace('/', '-')} klines {start} {end}.csv"

tt = binpan.Symbol(from_csv=klines_csv)
tt.df

2026-03-05	 21:31:18     INFO Loading LTCBTC 1m Europe-Madrid klines 1772682600000 1772742600000.csv

                                           Open time      Open      High       Low     Close  Volume                        Close time  Quote volume  Trades  Taker buy base volume  Taker buy quote volume  Ignore  Open timestamp  Close timestamp
LTCBTC 1m Europe/Madrid
2026-03-05 04:50:00+01:00  2026-03-05 04:50:00+01:00  0.000779  0.000779  0.000779  0.000779   0.167  2026-03-05 04:50:59.999000+01:00      0.000130       1                  0.167                0.000130       0   1772682600000    1772682659999
2026-03-05 04:51:00+01:00  2026-03-05 04:51:00+01:00  0.000778  0.000778  0.000778  0.000778   0.380  2026-03-05 04:51:59.999000+01:00      0.000296       1                  0.000                0.000000       0   1772682660000    1772682719999
2026-03-05 04:52:00+01:00  2026-03-05 04:52:00+01:00  0.000778  0.000778  0.000778  0.000778   0.000  2026-03-05 04:52:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772682720000    1772682779999
2026-03-05 04:53:00+01:00  2026-03-05 04:53:00+01:00  0.000778  0.000778  0.000778  0.000778   0.000  2026-03-05 04:53:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772682780000    1772682839999
2026-03-05 04:54:00+01:00  2026-03-05 04:54:00+01:00  0.000778  0.000778  0.000778  0.000778   0.000  2026-03-05 04:54:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772682840000    1772682899999
...                                              ...       ...       ...       ...       ...     ...                               ...           ...     ...                    ...                     ...     ...             ...              ...
2026-03-05 21:26:00+01:00  2026-03-05 21:26:00+01:00  0.000783  0.000783  0.000783  0.000783   0.158  2026-03-05 21:26:59.999000+01:00      0.000124       1                  0.000                0.000000       0   1772742360000    1772742419999
2026-03-05 21:27:00+01:00  2026-03-05 21:27:00+01:00  0.000784  0.000784  0.000784  0.000784   4.577  2026-03-05 21:27:59.999000+01:00      0.003588       2                  0.000                0.000000       0   1772742420000    1772742479999
2026-03-05 21:28:00+01:00  2026-03-05 21:28:00+01:00  0.000784  0.000784  0.000784  0.000784   0.000  2026-03-05 21:28:59.999000+01:00      0.000000       0                  0.000                0.000000       0   1772742480000    1772742539999
2026-03-05 21:29:00+01:00  2026-03-05 21:29:00+01:00  0.000785  0.000785  0.000785  0.000785   5.593  2026-03-05 21:29:59.999000+01:00      0.004390       8                  5.593                0.004390       0   1772742540000    1772742599999
2026-03-05 21:30:00+01:00  2026-03-05 21:30:00+01:00  0.000785  0.000785  0.000785  0.000785   5.719  2026-03-05 21:30:59.999000+01:00      0.004489       4                  4.825                0.003788       0   1772742600000    1772742659999

[1001 rows x 14 columns]

## Import Trades from CSV

Similarly, you can load aggregated or atomic trades from CSV using the `from_csv=True` parameter in `get_agg_trades()` or `get_atomic_trades()`.

In [9]:
# Build the agg trades filename
agg_csv = f"{sym.agg_trades.index.name.replace('/', '-')} aggTrades {start} {end}.csv"
tt.get_agg_trades(from_csv=agg_csv)
tt.agg_trades

Requesting aggregated trades between 2026-03-05 04:50:00 and 2026-03-05 21:30:00

                                  Aggregate tradeId     Price  Quantity  First tradeId  Last tradeId                 Date      Timestamp  Buyer was maker  Best price match
LTCBTC Europe/Madrid
2026-03-05 04:50:43.379000+01:00           81471983  0.000779     0.167      106789049     106789049  2026-03-05 04:50:43  1772682643379            False              True
2026-03-05 04:51:46.571000+01:00           81471984  0.000778     0.380      106789050     106789050  2026-03-05 04:51:46  1772682706571             True              True
2026-03-05 04:59:57.800000+01:00           81471985  0.000779     0.358      106789051     106789051  2026-03-05 04:59:57  1772683197800            False              True
2026-03-05 05:00:05.571000+01:00           81471986  0.000779     0.272      106789052     106789052  2026-03-05 05:00:05  1772683205571             True              True
2026-03-05 05:00:13.741000+01:00           81471987  0.000778     0.879      106789053     106789053  2026-03-05 05:00:13  1772683213741             True              True
...                                             ...       ...       ...            ...           ...                  ...            ...              ...               ...
2026-03-05 21:26:21.450000+01:00           81473611  0.000783     0.158      106791284     106791284  2026-03-05 21:26:21  1772742381450             True              True
2026-03-05 21:27:09.537000+01:00           81473612  0.000784     4.577      106791285     106791286  2026-03-05 21:27:09  1772742429537             True              True
2026-03-05 21:29:10.518000+01:00           81473613  0.000785     5.127      106791287     106791292  2026-03-05 21:29:10  1772742550518            False              True
2026-03-05 21:29:11.087000+01:00           81473614  0.000785     0.179      106791293     106791293  2026-03-05 21:29:11  1772742551087            False              True
2026-03-05 21:29:21.450000+01:00           81473615  0.000785     0.287      106791294     106791294  2026-03-05 21:29:21  1772742561450            False              True

[1633 rows x 9 columns]

In [10]:
# Build the atomic trades filename
atomic_csv = f"{sym.atomic_trades.index.name.replace('/', '-')} atomicTrades {start} {end}.csv"
tt.get_atomic_trades(from_csv=atomic_csv)
tt.atomic_trades

Requesting atomic trades between 2026-03-05 04:50:00 and 2026-03-05 21:30:00

                                   Trade Id     Price  Quantity  Quote quantity                 Date      Timestamp  Buyer was maker  Best price match
LTCBTC Europe/Madrid
2026-03-05 04:50:43.379000+01:00  106789049  0.000779     0.167        0.000130  2026-03-05 04:50:43  1772682643379            False              True
2026-03-05 04:51:46.571000+01:00  106789050  0.000778     0.380        0.000296  2026-03-05 04:51:46  1772682706571             True              True
2026-03-05 04:59:57.800000+01:00  106789051  0.000779     0.358        0.000279  2026-03-05 04:59:57  1772683197800            False              True
2026-03-05 05:00:05.571000+01:00  106789052  0.000779     0.272        0.000212  2026-03-05 05:00:05  1772683205571             True              True
2026-03-05 05:00:13.741000+01:00  106789053  0.000778     0.879        0.000684  2026-03-05 05:00:13  1772683213741             True              True
...                                     ...       ...       ...             ...                  ...            ...              ...               ...
2026-03-05 21:29:10.518000+01:00  106791290  0.000785     0.129        0.000101  2026-03-05 21:29:10  1772742550518            False              True
2026-03-05 21:29:10.518000+01:00  106791291  0.000785     1.518        0.001192  2026-03-05 21:29:10  1772742550518            False              True
2026-03-05 21:29:10.518000+01:00  106791292  0.000785     0.695        0.000546  2026-03-05 21:29:10  1772742550518            False              True
2026-03-05 21:29:11.087000+01:00  106791293  0.000785     0.179        0.000141  2026-03-05 21:29:11  1772742551087            False              True
2026-03-05 21:29:21.450000+01:00  106791294  0.000785     0.287        0.000225  2026-03-05 21:29:21  1772742561450            False              True

[2246 rows x 8 columns]

## Verify Imported Data

After importing from CSV, the `Symbol` instance contains the same DataFrames as if fetched from the API. You can plot, add indicators, or run analysis as usual.

In [11]:
tt.plot_agg_trades_size()

'/home/nando/PycharmProjects/binpan_studio_dev/notebooks/last_plot.png'

## Cleanup

Remove the CSV files generated during this tutorial.

In [12]:
import os

for csv_file in [klines_csv, agg_csv, atomic_csv]:
    if os.path.exists(csv_file):
        os.remove(csv_file)
        print(f"Deleted: {csv_file}")

Deleted: LTCBTC 1m Europe-Madrid klines 1772682600000 1772742600000.csv
Deleted: LTCBTC Europe-Madrid aggTrades 1772682600000 1772742600000.csv
Deleted: LTCBTC Europe-Madrid atomicTrades 1772682600000 1772742600000.csv